import { ALL_RELATIONS, RESEARCH_BY_PLAY } from "./db/index.ts";
import type {
  ActionDef,
  ActionGroup,
  EdgeDef,
  EndingId,
  EventChoice,
  EventDef,
  Evidence,
  NodeDef,
  StatKey,
} from "./types.ts";

export const STAT_META: Record<
  StatKey,
  { label: string; short: string; hint: string }
> = {
  etki: {
    label: "Koruma",
    short: "ETKİ",
    hint: "Siyasi kalkan. Düşerse inkâr tutulmaz.",
  },
  kara: {
    label: "Örtülü",
    short: "ÖRTÜ",
    hint: "Para, araç, sahte kimlik, operasyon bütçesi. Bitince saha aç kalır.",
  },
  giz: {
    label: "Gizlilik",
    short: "GİZ",
    hint: "En önemli bar. Sıfır olursa ifşa — kaybedersin.",
  },
  bilgi: {
    label: "Bilgi",
    short: "BİLGİ",
    hint: "Sisi açar. Çok artarsa gizlilik erir.",
  },
  saha: {
    label: "Saha",
    short: "SAHA",
    hint: "Tim ve itirafçı. Ağın fiilî gücü.",
  },
  sadakat: {
    label: "Sadakat",
    short: "SAD",
    hint: "Kişiler ve alt gruplar. Düşerse saha kendi başına iş yapar.",
  },
  kamuoyu: {
    label: "Kamuoyu",
    short: "KAMU",
    hint: "Basın ve meclis ısısı. Yükselirse gizlilik erir.",
  },
  hukuk: {
    label: "Hukuk",
    short: "HUK",
    hint: "Soruşturma yüzeyi. Ahlâk barı değil; resmi risk.",
  },
};

export const EVIDENCE_META: Record<
  Evidence,
  { label: string; hint: string }
> = {
  BELGELİ: {
    label: "BELGELİ",
    hint: "Kamu kaydı, kaza, kimlik, komisyon tutanağı.",
  },
  GÜÇLÜ: {
    label: "GÜÇLÜ",
    hint: "Çoklu tanıklık, kitap, iddianame hattı. Tek el değil.",
  },
  TARTIŞMALI: {
    label: "TARTIŞMALI",
    hint: "İddia var, emir/niyet boşluğu duruyor. Güçlendirmek ifşa pahalıdır.",
  },
  BOŞLUK: {
    label: "BOŞLUK",
    hint: "Kaynak sessiz. Uydurulmaz. Sis olarak kalır.",
  },
};

type RawNode = Omit<
  NodeDef,
  | "researchId"
  | "sourceIds"
  | "historicalFact"
  | "sourceClaim"
  | "gameReconstruction"
  | "motivationKind"
  | "motivation"
>;

const RAW_NODES: RawNode[] = [
  {
    id: "jitem",
    name: "JİTEM",
    kind: "kurum",
    faction: "jitem",
    role: "Jandarma istihbarat grup ve timleri. Fiilî yapı; resmi dil uzun yıllar ‘yok’ der.",
    evidence: "GÜÇLÜ",
    source: "Doğan; Ersever; tanıklıklar / iddianameler",
    dossier:
      "1986–88 civarı fiilî oluşum. Kesin kuruluş günü belgesi yok (BOŞLUK). Resmi inkâr BELGELİ’dir; fiilî varlık GÜÇLÜ’dür. Tek merkezli komplo kaynaklarca desteklenmez.",
    x: 250,
    y: 250,
    appearTurn: 1,
    bilgiReveal: 0,
  },
  {
    id: "mit",
    name: "MİT",
    kind: "kurum",
    faction: "mit",
    role: "Milli İstihbarat. İç hatlar homojen değil.",
    evidence: "GÜÇLÜ",
    source: "Pipo; Eymür yazıları; atin.org",
    dossier:
      "Abas–Eymür–Eken hattı kurumun tek sesi değildir. JİTEM ile sürekli eşgüdüm varsayılmaz. 1990 Abas suikastı bu hattı kırar.",
    x: 560,
    y: 130,
    appearTurn: 3,
    bilgiReveal: 18,
  },
  {
    id: "emniyet",
    name: "Emniyet",
    kind: "kurum",
    faction: "emniyet",
    role: "Polis özel tim / yeraltı kesişimi. JİTEM’den ayrı çıkar ağı.",
    evidence: "GÜÇLÜ",
    source: "Eymür uyarıları; Reis; Susurluk",
    dossier:
      "1993 sonrası Çatlı yükselişi bu koridorda ısınır. Jandarma hattını otomatik emir-komuta etmez.",
    x: 640,
    y: 340,
    appearTurn: 8,
    bilgiReveal: 36,
  },
  {
    id: "dogan",
    name: "Arif Doğan",
    kind: "kisi",
    faction: "jitem",
    role: "İdari / kurucu rol iddiası. ‘JİTEM’i ben kurdum.’",
    evidence: "GÜÇLÜ",
    source: "Kendi kitabı; Ergenekon süreci",
    dossier:
      "Saha hattının karşısında idari masa. 1990 ayrılış/devir iddiası GÜÇLÜ tanıklık, detay TARTIŞMALI.",
    x: 150,
    y: 160,
    appearTurn: 1,
    bilgiReveal: 0,
  },
  {
    id: "ersever",
    name: "A. Cem Ersever",
    kind: "kisi",
    faction: "jitem",
    role: "Saha hattı. İtirafçı timleri, sivil kıyafet operasyonları.",
    evidence: "GÜÇLÜ",
    source: "Binbaşı Ersever’in İtirafları (Yalçın)",
    dossier:
      "1980’ler ortası–1993. 1993 istifa + röportaj. Kasım 1993: kendisi, Nevval Boz ve bir itirafçı — cesetler BELGELİ. Fail Yeşil iddiası GÜÇLÜ. Emir kaynağı TARTIŞMALI.",
    x: 300,
    y: 390,
    appearTurn: 1,
    bilgiReveal: 0,
  },
  {
    id: "veli",
    name: "Veli Küçük",
    kind: "kisi",
    faction: "jitem",
    role: "1990 sonrası komuta hattı iddiası.",
    evidence: "TARTIŞMALI",
    source: "Tanıklıklar; Ersever bağlamı",
    dossier:
      "Doğan ayrılışı sonrası emir-komuta kayması GÜÇLÜ iddia / detay TARTIŞMALI. Ersever cinayeti emir kaynağı olarak Ankara/Küçük hattı TARTIŞMALI bırakılır.",
    x: 430,
    y: 190,
    appearTurn: 4,
    bilgiReveal: 28,
  },
  {
    id: "abas",
    name: "Hiram Abas",
    kind: "kisi",
    faction: "mit",
    role: "MİT operatörü. Profesyonel, kurumsal profil.",
    evidence: "GÜÇLÜ",
    source: "Pipo (Yalçın)",
    dossier:
      "26 Eylül 1990 İstanbul suikastı — ölüm BELGELİ. Takip ekibinin üç gün önce kaldırıldığı iddiası GÜÇLÜ/TARTIŞMALI. Fail ve emir zinciri bu masada kesinleştirilmez. JİTEM’e zorla bağlama TARTIŞMALI.",
    x: 640,
    y: 70,
    appearTurn: 3,
    bilgiReveal: 22,
  },
  {
    id: "eymur",
    name: "Mehmet Eymür",
    kind: "kisi",
    faction: "mit",
    role: "MİT Kontrterör. İçeriden uyarı yazan hat.",
    evidence: "GÜÇLÜ",
    source: "Eymür PDF’leri; atin.org",
    dossier:
      "Raporları bilgi asimetresini artırır, GİZ’i düşürebilir. Abas ve Eken ile MİT içi bağ GÜÇLÜ. JİTEM’in sözcüsü değildir.",
    x: 780,
    y: 130,
    appearTurn: 3,
    bilgiReveal: 16,
  },
  {
    id: "eken",
    name: "Korkut Eken",
    kind: "kisi",
    faction: "mit",
    role: "Özel tim / istihbarat kesişimi.",
    evidence: "GÜÇLÜ",
    source: "Pipo; Eymür",
    dossier:
      "Abas ve Eymür ile kaynaklarda geçer. Emniyet özel tim hattına yakın durur; JİTEM komuta zincirine yedirilmez.",
    x: 700,
    y: 220,
    appearTurn: 5,
    bilgiReveal: 30,
  },
  {
    id: "yesil",
    name: "Yeşil",
    kind: "kisi",
    faction: "jitem",
    role: "Mahmut Yıldırım. Operatif / tetikçi profili. Kendi başına karar verici değil.",
    evidence: "GÜÇLÜ",
    source: "Pekmezci; Aygan; Ersever bağlamı",
    dossier:
      "Ersever cinayeti faili iddiası GÜÇLÜ (çoklu tanıklık). Emir kaynağı TARTIŞMALI. Saha kapasitesini şişirir, GİZ’i yakar.",
    x: 380,
    y: 520,
    appearTurn: 2,
    bilgiReveal: 24,
  },
  {
    id: "aygan",
    name: "Abdülkadir Aygan",
    kind: "kisi",
    faction: "jitem",
    role: "İtirafçı tim. Sonradan tanık.",
    evidence: "GÜÇLÜ",
    source: "Tanıklık",
    dossier:
      "Ersever saha hattının itirafçı katmanı. Kapasite artırır; konuşursa BİLGİ patlar.",
    x: 180,
    y: 510,
    appearTurn: 2,
    bilgiReveal: 12,
  },
  {
    id: "catli",
    name: "Abdullah Çatlı",
    kind: "kisi",
    faction: "emniyet",
    role: "Ülkücü geçmiş, sahte kimlik, devlet–mafya kesişimi.",
    evidence: "GÜÇLÜ",
    source: "Reis (Yalçın); Susurluk",
    dossier:
      "JİTEM saha hattının uzantısı değildir. 1993–96 Emniyet–yeraltı yükselişi. Kocadağ ve Bucak ile 3 Kasım 1996 — BELGELİ.",
    x: 820,
    y: 400,
    appearTurn: 8,
    bilgiReveal: 40,
  },
  {
    id: "kocadag",
    name: "Hüseyin Kocadağ",
    kind: "kisi",
    faction: "emniyet",
    role: "Emniyet. Susurluk aracındaki resmi yüz.",
    evidence: "BELGELİ",
    source: "Susurluk kazası",
    dossier:
      "Çatlı ile operasyonel ortaklık kazada kilitlenir. Öncesi GÜÇLÜ, kaza BELGELİ.",
    x: 700,
    y: 500,
    appearTurn: 8,
    bilgiReveal: 42,
  },
  {
    id: "bucak",
    name: "Sedat Bucak",
    kind: "kisi",
    faction: "emniyet",
    role: "Milletvekili / aşiret. Siyasi koridor.",
    evidence: "BELGELİ",
    source: "Susurluk kazası",
    dossier:
      "Çatlı–Kocadağ–Bucak aynı araçta. Siyaset–yeraltı kesişiminin görünür halkası. ETKİ’yi hem taşır hem yakar.",
    x: 900,
    y: 500,
    appearTurn: 9,
    bilgiReveal: 48,
  },
  {
    id: "gonca",
    name: "Gonca Us",
    kind: "kisi",
    faction: "emniyet",
    role: "Çatlı’nın yanında. Susurluk’ta birlikte.",
    evidence: "GÜÇLÜ",
    source: "Susurluk + sınırlı rekonstrüksiyon",
    dossier:
      "İlişki ≈1995 sonu / 1996 başı. Birlikte ölüm GÜÇLÜ; kişisel detay ZAYIF. Ağın sivil görünürlük maliyetidir.",
    x: 900,
    y: 340,
    appearTurn: 9,
    bilgiReveal: 50,
  },
  {
    id: "guneydogu",
    name: "Güneydoğu saha",
    kind: "koridor",
    faction: "jitem",
    role: "Koridor. Tim, itirafçı, sivil kıyafet. Harita odasının asıl yüzü.",
    evidence: "GÜÇLÜ",
    source: "Doğan; Ersever",
    dossier:
      "PKK silahlı mücadelesinin yükseldiği zemin. Yapı burada fiilen doğar. Ankara’nın bildiği ile sahanın yaptığı aynı değildir.",
    x: 120,
    y: 360,
    appearTurn: 1,
    bilgiReveal: 0,
  },
  {
    id: "agar",
    name: "Mehmet Ağar",
    kind: "kisi",
    faction: "siyaset",
    role: "Emniyet / siyaset koridoru. JİTEM komuta zinciri değil.",
    evidence: "GÜÇLÜ",
    source: "TBMM Susurluk; Reis",
    dossier:
      "Siyasi kalkan. Çatlı kesişimi GÜÇLÜ iddia, emir TARTIŞMALI. Geç açılır.",
    x: 980,
    y: 260,
    appearTurn: 8,
    bilgiReveal: 38,
  },
  {
    id: "sahin",
    name: "İbrahim Şahin",
    kind: "kisi",
    faction: "emniyet",
    role: "Özel harekât. JİTEM uzantısı değil.",
    evidence: "GÜÇLÜ",
    source: "TBMM tutanakları",
    dossier: "Emniyet saha yüzü. Çatlı kesişimi kaynaklı; jandarma emri yok.",
    x: 760,
    y: 560,
    appearTurn: 8,
    bilgiReveal: 40,
  },
];

export const NODES: NodeDef[] = RAW_NODES.map((n) => {
  const r = RESEARCH_BY_PLAY[n.id];
  return {
    ...n,
    researchId: r?.id ?? `play_${n.id}`,
    sourceIds: r?.sourceIds ?? [],
    historicalFact: r?.provenance.historicalFact ?? n.dossier,
    sourceClaim: r?.provenance.sourceClaim ?? n.source,
    gameReconstruction: r?.provenance.gameReconstruction ?? n.role,
    motivationKind: r?.motivation.kind ?? "unknown",
    motivation: r?.motivation.text ?? "Kaynaklar niyeti kapatmaz.",
  };
});

type RawEdge = Omit<EdgeDef, "researchId" | "sourceIds" | "layer">;

const RAW_EDGES: RawEdge[] = [
  {
    id: "dogan-ersever",
    from: "dogan",
    to: "ersever",
    label: "idari / saha",
    evidence: "GÜÇLÜ",
    source: "Doğan + Ersever anlatımı",
    appearTurn: 1,
  },
  {
    id: "dogan-jitem",
    from: "dogan",
    to: "jitem",
    label: "kurucu iddiası",
    evidence: "GÜÇLÜ",
    source: "Doğan kitabı",
    appearTurn: 1,
  },
  {
    id: "ersever-jitem",
    from: "ersever",
    to: "jitem",
    label: "saha hattı",
    evidence: "GÜÇLÜ",
    source: "Ersever; tanıklıklar",
    appearTurn: 1,
  },
  {
    id: "ersever-guneydogu",
    from: "ersever",
    to: "guneydogu",
    label: "operatif koridor",
    evidence: "GÜÇLÜ",
    source: "Ersever",
    appearTurn: 1,
  },
  {
    id: "jitem-guneydogu",
    from: "jitem",
    to: "guneydogu",
    label: "fiilî zemin",
    evidence: "GÜÇLÜ",
    source: "Doğan; Ersever",
    appearTurn: 1,
  },
  {
    id: "ersever-aygan",
    from: "ersever",
    to: "aygan",
    label: "itirafçı tim",
    evidence: "GÜÇLÜ",
    source: "Aygan tanıklığı",
    appearTurn: 2,
  },
  {
    id: "ersever-yesil",
    from: "ersever",
    to: "yesil",
    label: "operatif",
    evidence: "GÜÇLÜ",
    source: "Aygan + Ersever + Pekmezci",
    appearTurn: 2,
  },
  {
    id: "abas-eymur",
    from: "abas",
    to: "eymur",
    label: "MİT içi",
    evidence: "GÜÇLÜ",
    source: "Pipo; Eymür",
    appearTurn: 3,
  },
  {
    id: "abas-mit",
    from: "abas",
    to: "mit",
    label: "operatör",
    evidence: "GÜÇLÜ",
    source: "Pipo",
    appearTurn: 3,
  },
  {
    id: "eymur-mit",
    from: "eymur",
    to: "mit",
    label: "kontrterör",
    evidence: "GÜÇLÜ",
    source: "Eymür yazıları",
    appearTurn: 3,
  },
  {
    id: "ersever-veli",
    from: "ersever",
    to: "veli",
    label: "1990 komuta",
    evidence: "TARTIŞMALI",
    source: "Tanıklıklar",
    appearTurn: 4,
  },
  {
    id: "veli-jitem",
    from: "veli",
    to: "jitem",
    label: "devir iddiası",
    evidence: "TARTIŞMALI",
    source: "Tanıklıklar",
    appearTurn: 4,
  },
  {
    id: "abas-eken",
    from: "abas",
    to: "eken",
    label: "MİT / özel",
    evidence: "GÜÇLÜ",
    source: "Pipo",
    appearTurn: 5,
  },
  {
    id: "eken-mit",
    from: "eken",
    to: "mit",
    label: "özel tim kesişimi",
    evidence: "GÜÇLÜ",
    source: "Pipo; Eymür",
    appearTurn: 5,
  },
  {
    id: "eymur-emniyet",
    from: "eymur",
    to: "emniyet",
    label: "uyarı / kesişim",
    evidence: "GÜÇLÜ",
    source: "Eymür raporları",
    appearTurn: 8,
  },
  {
    id: "catli-emniyet",
    from: "catli",
    to: "emniyet",
    label: "özel tim hattı",
    evidence: "GÜÇLÜ",
    source: "Reis; Eymür",
    appearTurn: 8,
  },
  {
    id: "catli-kocadag",
    from: "catli",
    to: "kocadag",
    label: "operasyonel ortak",
    evidence: "BELGELİ",
    source: "Susurluk kazası",
    appearTurn: 8,
    belgelıLockTurn: 10,
  },
  {
    id: "kocadag-emniyet",
    from: "kocadag",
    to: "emniyet",
    label: "kurum içi",
    evidence: "BELGELİ",
    source: "Susurluk",
    appearTurn: 8,
  },
  {
    id: "catli-bucak",
    from: "catli",
    to: "bucak",
    label: "kesişim",
    evidence: "BELGELİ",
    source: "Susurluk kazası",
    appearTurn: 9,
    belgelıLockTurn: 10,
  },
  {
    id: "catli-gonca",
    from: "catli",
    to: "gonca",
    label: "kişisel / fayda",
    evidence: "GÜÇLÜ",
    source: "Susurluk + sınırlı detay",
    appearTurn: 9,
    belgelıLockTurn: 10,
  },
  {
    id: "agar-emniyet",
    from: "agar",
    to: "emniyet",
    label: "siyaset / emniyet",
    evidence: "GÜÇLÜ",
    source: "TBMM",
    appearTurn: 8,
  },
  {
    id: "sahin-emniyet",
    from: "sahin",
    to: "emniyet",
    label: "özel harekât",
    evidence: "GÜÇLÜ",
    source: "TBMM",
    appearTurn: 8,
  },
  {
    id: "sahin-catli",
    from: "sahin",
    to: "catli",
    label: "kesişim",
    evidence: "GÜÇLÜ",
    source: "Susurluk bağlamı",
    appearTurn: 8,
  },
  {
    id: "agar-catli",
    from: "agar",
    to: "catli",
    label: "koruma iddiası",
    evidence: "TARTIŞMALI",
    source: "komisyon iddiaları",
    appearTurn: 8,
  },
];

export const EDGES: EdgeDef[] = RAW_EDGES.map((e) => {
  const r = ALL_RELATIONS.find((x) => x.playId === e.id);
  return {
    ...e,
    researchId: r?.id ?? `rel_${e.id}`,
    sourceIds: r?.sourceIds ?? [],
    layer: r?.layer ?? "sourceClaim",
  };
});

export const ACTIONS: ActionDef[] = [
  { id: "tim_kur", name: "Tim kur", blurb: "Sahaya adam koy. Resmi kayıt açılmaz.", cost: "Saha + · Örtülü − · Giz −", risk: "İz kalır", group: "saha", needs: "none", authority: "command", ap: 1 },
  { id: "itirafci_al", name: "İtirafçı al", blurb: "İçeriden bilgi. Konuşursa giz yanar.", cost: "Saha + · Bilgi + · Giz −−", risk: "Tanıklık", group: "saha", needs: "none", authority: "command", ap: 1 },
  { id: "saha_op", name: "Operasyon", blurb: "Sonuç soyut. Kapasite yoksa sızıntı.", cost: "Örtülü + · Giz −", risk: "Zayıfsa ifşa", group: "saha", needs: "none", authority: "command", ap: 1 },
  { id: "kara_topla", name: "Örtülü topla", blurb: "Lojistik, kimlik, araç. İz bırakır.", cost: "Örtülü ++ · Giz − · Koruma −", risk: "İz", group: "saha", needs: "none", authority: "command", ap: 1 },
  { id: "sizinti_bastir", name: "Sızıntı kes", blurb: "İnkârı tut. Kaseti yok etmez.", cost: "Giz ++ · Koruma − · Bilgi −", risk: "Asimetri daralır", group: "koruma", needs: "none", authority: "command", ap: 1 },
  { id: "inkar_yaz", name: "‘Yok’ de", blurb: "Resmi dil: yapı yoktur.", cost: "Giz + · Bilgi −", risk: "Hukuk ısınabilir", group: "koruma", needs: "none", authority: "command", ap: 1 },
  { id: "medya_kes", name: "Basını kes", blurb: "Haber sızmasın. Koruma harcar.", cost: "Giz + · Koruma −", risk: "Kamuoyu tepkisi", group: "koruma", needs: "none", authority: "influence", ap: 1 },
  { id: "ankara_koru", name: "Ankara kalkanı", blurb: "Kurumsal koruma. Örtülü öder.", cost: "Koruma ++ · Örtülü −", risk: "Siyasi iz", group: "koruma", needs: "none", authority: "influence", ap: 1 },
  { id: "rapor_yaz", name: "Rapor yaz", blurb: "Eymür tipi. Sis açılır, giz çatlar.", cost: "Bilgi ++ · Giz −−", risk: "İfşa", group: "bilgi", needs: "none", authority: "influence", ap: 1 },
  { id: "dosya_oku", name: "Dosya oku", blurb: "Hafif bakış. Az sis, az risk.", cost: "Bilgi + · Giz −", risk: "Düşük", group: "bilgi", needs: "none", authority: "command", ap: 1 },
  { id: "bag_guclendir", name: "Bağı sıkılaştır", blurb: "Haritada çizgi seç. Yeni hat yok.", cost: "Giz −  (TARTIŞMALI −−)", risk: "Sızıntı yüzeyi", group: "ag", needs: "edge", authority: "command", ap: 1 },
  { id: "bag_gevset", name: "Bağı gevşet", blurb: "Mesafe. Kişi bağımsızlaşabilir.", cost: "Giz + · Saha −", risk: "Sadakat −", group: "ag", needs: "edge", authority: "command", ap: 1 },
  { id: "bag_gozet", name: "Bağı gözet", blurb: "Değiştirme. Kısmi bilgi al.", cost: "Bilgi + · Giz −", risk: "İz", group: "ag", needs: "edge", authority: "command", ap: 1, unlockAct: 3 },
  { id: "bag_yalitim", name: "Bağı yalıt", blurb: "Sekiz duvar. Kapasite düşer.", cost: "Giz + · Saha −", risk: "Kopuş", group: "ag", needs: "edge", authority: "command", ap: 1, unlockAct: 3 },
  { id: "bag_ifsa", name: "Bağı ifşa et", blurb: "Kamu ısınır. Çıpa durmaz.", cost: "Kamu + · Hukuk + · Giz −−", risk: "Görünürlük", group: "ag", needs: "edge", authority: "influence", ap: 1, unlockAct: 5 },
  { id: "bag_arabul", name: "Arabul", blurb: "Gerilimi düşür. Güven toparlar.", cost: "Sadakat + · Giz −", risk: "İz", group: "ag", needs: "edge", authority: "command", ap: 1, unlockAct: 3 },
  { id: "bag_koru", name: "Bağı koru", blurb: "Sızıntı yüzeyini kapa. Kapasite bağlanır.", cost: "Giz + · Saha −", risk: "Bağımlılık", group: "ag", needs: "edge", authority: "command", ap: 1, unlockAct: 3 },
  { id: "rakip_sogut", name: "Rakibi soğut", blurb: "MİT veya Emniyet. Eşgüdüm yok.", cost: "Koruma − · Örtülü −", risk: "Kin", group: "ag", needs: "faction", authority: "influence", ap: 1 },
  { id: "kisi_koru", name: "Kişiyi koru", blurb: "Haritadan isim. Sadakat artar, saha bağlanır.", cost: "Sadakat + · Giz + · Saha −", risk: "Kapasite düşer", group: "kisi", needs: "node", authority: "command", ap: 1 },
  { id: "kisi_kullan", name: "Kişiyi kullan", blurb: "Fayda al. Sadakat incelir.", cost: "Saha + · Sadakat − · Giz −", risk: "Kopuş", group: "kisi", needs: "node", authority: "command", ap: 1 },
  { id: "kisi_harca", name: "Kişiyi harca", blurb: "Bilgi için yak. Geri dönüşü sert.", cost: "Bilgi + · Sadakat −− · Giz −−", risk: "Konuşma / kin", group: "kisi", needs: "node", authority: "command", ap: 1 },
  { id: "kisi_mesafe", name: "Mesafe koy", blurb: "Kişiden uzaklaş. İz küçülür.", cost: "Giz + · Sadakat −", risk: "Bağımsız hareket", group: "kisi", needs: "node", authority: "command", ap: 1 },
  { id: "soru_yonlendir", name: "Soruşturmayı sapıt", blurb: "Dosyayı kendi hattına kaydır. Durdurmaz.", cost: "Hukuk + · Koruma −", risk: "İz", group: "koruma", needs: "none", authority: "influence", ap: 1, unlockAct: 4 },
  { id: "soru_sinir", name: "Soruşturmayı sınırla", blurb: "Dar tut. Söndürmez. Isı düşer.", cost: "Hukuk − · Giz +", risk: "Kin / kamu", group: "koruma", needs: "none", authority: "influence", ap: 1, unlockAct: 4 },
  { id: "soru_ac", name: "Yüzeyi aç", blurb: "Kamu öne. Giz yanar. Çıpa durmaz.", cost: "Kamu + · Hukuk + · Giz −−", risk: "Görünürlük", group: "bilgi", needs: "none", authority: "influence", ap: 1, unlockAct: 4 },
];

export const ACTION_GROUPS: { id: ActionGroup; label: string; hint: string }[] = [
  { id: "saha", label: "Saha", hint: "Tim, itirafçı, lojistik" },
  { id: "koruma", label: "Koruma", hint: "İnkâr ve sızıntı" },
  { id: "bilgi", label: "Bilgi", hint: "Sis açılır, giz incelir" },
  { id: "ag", label: "Ağ", hint: "Bağlar ve diğer hatlar" },
  { id: "kisi", label: "Kişi", hint: "Koru / kullan / harca / mesafe" },
];

export const EVENT_CHOICES: Record<number, EventChoice[]> = {
  1: [
    { id: "e1-saha", label: "Saha timlerini büyüt", hint: "Ersever tipi. Kapasite artar, iz kalır.", log: "Duruş: saha büyüdü. Resmi kayıt yok.", effects: { saha: 8, giz: -4 } },
    { id: "e1-idari", label: "İdari kalkan ör", hint: "Doğan tipi. Koruma kalın, saha mesafeli.", log: "Duruş: idari kalkan. İnkâr dili önde.", effects: { etki: 8, giz: 2, saha: -2 } },
    { id: "e1-izle", label: "Sadece izle", hint: "Az iz, az güç. Sis durur.", log: "Duruş: mesafe. Masa izliyor.", effects: { bilgi: 4, giz: 2 } },
  ],
  2: [
    { id: "e2-al", label: "İtirafçı katmanını al", hint: "Bilgi ve saha. Konuşma riski.", log: "Duruş: itirafçı alındı.", effects: { saha: 6, bilgi: 5, giz: -5 } },
    { id: "e2-resmi", label: "Resmi birlikle yetin", hint: "Daha az iz, daha az kapasite.", log: "Duruş: resmi hat. İtirafçı sınırlı.", effects: { giz: 5, saha: -3 } },
    { id: "e2-sik", label: "Az konuştur, sıkı tut", hint: "Orta yol.", log: "Duruş: sıkı denetim.", effects: { giz: 3, saha: 2, bilgi: -2 } },
  ],
  3: [
    { id: "e3-oku", label: "Eymür uyarısını oku", hint: "Sis açılır. Giz incelir.", log: "Duruş: MİT içi not okundu. JİTEM emri değil.", effects: { bilgi: 8, giz: -5 } },
    { id: "e3-mesafe", label: "MİT’e mesafe koy", hint: "Eşgüdüm yok. Sadece uzak dur.", log: "Duruş: MİT hattı soğutuldu.", effects: { etki: 3, giz: 2 }, special: "mit-cool" },
    { id: "e3-karisma", label: "Karışma", hint: "Kendi işine bak.", log: "Duruş: MİT içi işine girilmedi.", effects: { giz: 4, bilgi: -2 } },
  ],
  4: [
    { id: "e4-saha", label: "Ersever’i sahada tut", hint: "Kapasite kalır, koruma incelir.", log: "Duruş: saha hattı bırakılmadı.", effects: { saha: 6, etki: -3 } },
    { id: "e4-uy", label: "Yeni komutaya uy", hint: "Kalkan artar. Saha uzaklaşır.", log: "Duruş: devir kabul. Detay TARTIŞMALI.", effects: { etki: 5, saha: -3, giz: -2 } },
    { id: "e4-not", label: "Kopuşu not et", hint: "Bilgi artar, giz düşer.", log: "Duruş: kayma dosyalandı. Emir uydurulmadı.", effects: { bilgi: 6, giz: -6 } },
  ],
  5: [
    { id: "e5-not", label: "MİT şokunu not et", hint: "Asimetri artar. Bağ uydurulmaz.", log: "Duruş: Abas kırılması not edildi. Fail TARTIŞMALI bırakıldı.", effects: { bilgi: 7 } },
    { id: "e5-mesafe", label: "Cenaze mesafesi", hint: "Profesyonel kanada yaklaşma.", log: "Duruş: mesafe. JİTEM zafer saymadı.", effects: { giz: 4, etki: 2 } },
    { id: "e5-zorla", label: "Zorla bağlama iddiasına yaklaşma", hint: "TARTIŞMALI. İfşa pahalı. Hat yaratılmaz.", log: "Duruş: JİTEM’e zorla bağlama yok. İddia TARTIŞMALI kaldı.", effects: { giz: 3, bilgi: 2 } },
  ],
  6: [
    { id: "e6-bas", label: "Bastır", hint: "Kaseti yok etmez. Hasarı keser.", log: "Duruş: sızıntı bastırıldı. Konuşma durmadı, GİZ hasarı kesildi.", effects: { giz: 6, etki: -8 }, special: "leak-suppress" },
    { id: "e6-not", label: "Konuşsun, not al", hint: "Bilgi patlar, giz yanar.", log: "Duruş: kaset tutuldu. İçeriden kırılma.", effects: { bilgi: 10, giz: -8 } },
    { id: "e6-yumusa", label: "Araya gir, yumuşat", hint: "Orta hasar.", log: "Duruş: yumuşatma. Kaset var, dil ölçülü.", effects: { giz: 3, bilgi: 4, etki: -4 }, special: "leak-suppress" },
  ],
  7: [
    { id: "e7-tut", label: "Saha hattını dağıtma", hint: "Kapasite kalsın.", log: "Duruş: saha kapanmadı. Kahraman yok.", effects: { saha: 5, giz: -3 } },
    { id: "e7-inkar", label: "İnkâr diline çek", hint: "Resmen yok. Kapasite düşer.", log: "Duruş: inkâr. Saha geri çekildi.", effects: { giz: 8, saha: -4 } },
    { id: "e7-dosya", label: "Yeşil iddiasını dosyala", hint: "Fail GÜÇLÜ. Emir TARTIŞMALI — uydurulmaz.", log: "Duruş: fail iddiası dosyalandı. Emir boşluğu duruyor.", effects: { bilgi: 6, giz: -4 } },
  ],
  8: [
    { id: "e8-sogut", label: "Kesişimi soğut", hint: "Emniyet hattını yavaşlat.", log: "Duruş: Emniyet–yeraltı soğutuldu. JİTEM uzantısı değil.", effects: { giz: 3, kara: -4 }, special: "emniyet-cool" },
    { id: "e8-fayda", label: "Faydayı kullan", hint: "Para döner, giz yer.", log: "Duruş: Çatlı hattı fayda olarak işlendi. Eşgüdüm uydurulmadı.", effects: { kara: 8, giz: -6 } },
    { id: "e8-eymur", label: "Eymür uyarısını dinle", hint: "Sis açılır.", log: "Duruş: uyarı okundu. İki hat ayrı kaldı.", effects: { bilgi: 8, giz: -5 } },
  ],
  9: [
    { id: "e9-gevse", label: "Kareyi gevşet", hint: "Çatlı bağlarını gevşet. Kaza takvimi durmaz.", log: "Duruş: kesişim gevşetildi. 3 Kasım takvimi durmadı.", effects: { giz: 4, etki: -2 }, special: "weaken-catli" },
    { id: "e9-gormez", label: "Görmezden gel", hint: "Kısa koruma, uzun risk.", log: "Duruş: görmezden gelindi. Ağ aynı karede birikiyor.", effects: { etki: 4, giz: -3 } },
    { id: "e9-uyari", label: "Uyarıyı ilet", hint: "Bilgi artar.", log: "Duruş: uyarı iletildi. BELGELİ kilit henüz yok.", effects: { bilgi: 6, giz: -4, etki: -3 } },
  ],
  10: [
    { id: "e10-inkar", label: "İnkâr et", hint: "Kaza durmaz. Dil tutulur.", log: "Duruş: inkâr. 3 Kasım görünürlüğü geldi.", effects: { giz: 6, etki: -8 } },
    { id: "e10-komisyon", label: "Komisyonla idare et", hint: "Siyasi kalkan, giz incelir.", log: "Duruş: TBMM/kamuoyu idaresi. Parçalı itiraf.", effects: { etki: 4, giz: -4 } },
    { id: "e10-parca", label: "Parçalı dağıt", hint: "Tek karede durma.", log: "Duruş: parçalı dağıtım. Tek el yoktu.", effects: { saha: -3, giz: 3, etki: 2 } },
  ],
};
type RawEvent = Omit<EventDef, "familyId" | "layer" | "anchor">;

const RAW_EVENTS: RawEvent[] = [
  {
    id: "e1",
    turn: 1,
    year: "1986–88",
    block: "B",
    title: "Fiilî oluşum",
    fileNo: "B-01/JİTEM",
    body: "Güneydoğu’da güvenlik bozulmuştur. Jandarma istihbarat içinde resmi olmayan ama fiilî bir yapı şekillenir: gruplar, timler, itirafçılar. Arif Doğan idari tarafta konuşulur. Ersever saha tarafında büyür. Resmi dil ‘yok’ der. Fiilî dil çalışmaya başlar.",
    hidden:
      "Kesin kuruluş günü belgesi yok. Siyasi zirvenin tam bilgi ve onay derecesi BOŞLUK. Tek el komplo bu dosyada üretilmez.",
    hiddenBilgi: 20,
    evidence: "GÜÇLÜ",
    revealNodeIds: ["jitem", "dogan", "ersever", "guneydogu"],
  },
  {
    id: "e2",
    turn: 2,
    year: "1988",
    block: "B",
    title: "İtirafçı katmanı",
    fileNo: "B-02/SAHA",
    body: "Saha, resmi birliğin yetmediği yerde itirafçı timleriyle genişler. Aygan hattı kapasite olarak görünür. Yeşil henüz gölgede bir operatif profilidir. Tim, Reis’ten fazla katmandır.",
    hidden:
      "Her faili meçhulün yazılı emirle yapıldığı iddiası ZAYIF’tır. Bu masada cinayet envanteri tutulmaz; kapasite tutulur.",
    hiddenBilgi: 28,
    evidence: "GÜÇLÜ",
    revealNodeIds: ["aygan", "yesil"],
  },
  {
    id: "e3",
    turn: 3,
    year: "1989",
    block: "B",
    title: "MİT içi hat",
    fileNo: "B-03/MİT",
    body: "MİT tek yürek değildir. Hiram Abas profesyonel operatör profilindedir. Mehmet Eymür kontrterörden izler, yazar. İki hat JİTEM’i henüz tam olarak kendi işi saymaz. Parçalı çıkar.",
    hidden:
      "Eymür–Abas gerilimi kurum içi meseledir. Jandarma masasına otomatik bağlanmaz. Bilgi asimetresi burada başlar.",
    hiddenBilgi: 24,
    evidence: "GÜÇLÜ",
    revealNodeIds: ["mit", "abas", "eymur"],
  },
  {
    id: "e4",
    turn: 4,
    year: "1990",
    block: "C",
    title: "Komuta kayması",
    fileNo: "C-01/DEVİR",
    body: "Dosyalar el değiştirir. Haritalar aynı kalır. Arif Doğan idari hattan çekilir; Veli Küçük hattı konuşulmaya başlar. Ersever sahada kalır. Kimileri buna devir der, kimileri kayma, kimileri hiçbir şey demez.",
    hidden:
      "İdari seviye ile saha operatörünün bildikleri farklıdır. Kim ne kadar sorumlu, kim ne kadar haberdar — net değildir. Detay TARTIŞMALI.",
    hiddenBilgi: 32,
    evidence: "TARTIŞMALI",
    revealNodeIds: ["veli"],
  },
  {
    id: "e5",
    turn: 5,
    year: "26 Eyl 1990",
    block: "C",
    title: "Abas hattı kırılır",
    fileNo: "C-02/ABAS",
    body: "İstanbul. Hiram Abas suikastta ölür. Aynı yıl içinde suikasta uğrayan ikinci MİT görevlisidir. Cenazede Eymür ve Eken vardır. MİT profesyonel kanadı sarsılır. Jandarma hattı bunu kendi zaferi sanmamalıdır.",
    hidden:
      "Tanıklara göre üç kişi. Bölgedeki takip ekibinin üç gün önce kaldırıldığı söylenir. Fail ve emir zinciri TARTIŞMALI bırakılır. JİTEM’e zorla bağlama — TARTIŞMALI.",
    hiddenBilgi: 40,
    evidence: "BELGELİ",
    revealNodeIds: ["eken"],
  },
  {
    id: "e6",
    turn: 6,
    year: "Haz 1993",
    block: "C",
    title: "Ersever konuşur",
    fileNo: "C-03/KASED",
    body: "9–14 Haziran 1993. Kasetler döner. Ersever, Soner Yalçın’a anlatır: timler, itirafçılar, sivil kıyafet. Yıllardır ‘yok’ denilen yapının içinden cümleler çıkar. Resmi dil çatlar.",
    hidden:
      "Konuşan içerideki, BİLGİ’yi patlatır ve GİZ’i yakar. Bastırma GİZ kaybını azaltır; kaseti yok etmez. Bu eşik tarihidir.",
    hiddenBilgi: 20,
    evidence: "GÜÇLÜ",
    revealNodeIds: [],
  },
  {
    id: "e7",
    turn: 7,
    year: "Kas 1993",
    block: "C",
    title: "Saha hattı kapanır",
    fileNo: "C-04/ERSEVER",
    body: "Kasım 1993. Ahmet Cem Ersever, Nevval Boz ve bir itirafçı öldürülür. Cesetler bulunur. Saha hattının konuşan ucu kapanır. Masa, kahraman gömmez; kapasite ve sızıntı hesabı yapar.",
    hidden:
      "Fail olarak Yeşil — GÜÇLÜ (çoklu tanıklık). Emir kaynağı Veli Küçük / Ankara — TARTIŞMALI. Bu dosyada emir uydurulmaz.",
    hiddenBilgi: 36,
    evidence: "BELGELİ",
    revealNodeIds: [],
  },
  {
    id: "e8",
    turn: 8,
    year: "1994–95",
    block: "D",
    title: "Çatlı yükselişi",
    fileNo: "D-01/EMNİYET",
    body: "Jandarma saha hattı yaralıdır. Boşluğu Emniyet–yeraltı kesişimi doldurur. Abdullah Çatlı sahte kimliklerle ısınır. Kocadağ resmi yüz olarak görünür. Eymür uyarı yazmaya devam eder. Bu, JİTEM’in uzantısı değil ayrı bir çıkar ağıdır.",
    hidden:
      "Özel tim hattı ile jandarma istihbarat aynı masa değildir. Eşgüdüm varsayımı TARTIŞMALI’dır ve ifşa pahalıdır.",
    hiddenBilgi: 38,
    evidence: "GÜÇLÜ",
    revealNodeIds: ["emniyet", "catli", "kocadag"],
  },
  {
    id: "e9",
    turn: 9,
    year: "1995–96",
    block: "D",
    title: "Kesişim birikir",
    fileNo: "D-02/GONCA",
    body: "Çatlı zirveye yaklaşmıştır. Yanında Gonca Us vardır. Bucak siyasi koridor olarak bağın ucuna gelir. Eymür uyarıları birikir. Araç henüz yolda değildir; ağ ise fiilen aynı kareye toplanmaktadır.",
    hidden:
      "Gonca ilişkisi ≈1 yıl. Detay sınırlıdır. BELGELİ kilit 3 Kasım’da atılır. Oyuncu yeni efsane bağ uyduramaz; var olanı gevşetebilir veya sıkılaştırabilir.",
    hiddenBilgi: 44,
    evidence: "GÜÇLÜ",
    revealNodeIds: ["gonca", "bucak"],
  },
  {
    id: "e10",
    turn: 10,
    year: "3 Kas 1996",
    block: "E",
    title: "Görünürlük şoku",
    fileNo: "E-01/SUSURLUK",
    body: "Balıkesir–Susurluk yolu. Gece. Mercedes bir kamyonla çarpışır. İçinde Kocadağ, Bucak, Çatlı, Gonca Us. Silahlar, kimlikler, belgeler. Yıllarca ‘yok’ denilen ilişkiler bir kaza ile görünür hale gelir. Susurluk bir başlangıç değildir. Bir sonuçtur.",
    hidden:
      "Çatlı–Kocadağ–Bucak–Gonca bağları BELGELİ kilitlenir. TBMM komisyonu, inkâr, parçalı itiraf. Tek doğru komplo çözümü yoktur. Masa ya kontrollü parçalanmayı taşır ya görünürlükte yanar.",
    hiddenBilgi: 10,
    evidence: "BELGELİ",
    revealNodeIds: [],
  },
];

const EVENT_LAYER: Record<number, EventDef["layer"]> = {
  1: "sourceClaim",
  2: "sourceClaim",
  3: "sourceClaim",
  4: "sourceClaim",
  5: "historicalFact",
  6: "sourceClaim",
  7: "historicalFact",
  8: "sourceClaim",
  9: "sourceClaim",
  10: "historicalFact",
};

export const EVENTS: EventDef[] = RAW_EVENTS.map((e) => ({
  ...e,
  familyId: `fam_${e.id}`,
  layer: EVENT_LAYER[e.turn] ?? "gameReconstruction",
  anchor: [5, 7, 10].includes(e.turn),
}));

export const ENDINGS: Record<
  EndingId,
  { title: string; verdict: string; body: string; win: boolean }
> = {
  inkar_ayakta: {
    title: "Ağ fiilen çalıştı",
    verdict: "KONTROL",
    win: true,
    body: "1986–96 boyunca masa, resmi ‘yok’ dilini ayakta tuttu. Saha kapasitesi düşmedi. 3 Kasım görünürlüğü geldi; ama parça parça çıkar ağları henüz tek dosyada erimedi. Kazanmak, komployu çözmek değil, inkâr ile fiilî yapıyı aynı anda taşımak demekti.",
  },
  kontrollu_parcalanma: {
    title: "Kontrollü parçalanma",
    verdict: "GECİKME",
    win: true,
    body: "GİZ inceldi, hatlar birbirini gördü, yine de komuta felakete dönmedi. Susurluk şoku geldi. Masa yıkılmayı erteledi. Bu da bir sonuçtur: tek el yoktu; parçalar kendi çıkarlarıyla dağıldı.",
  },
  giz_coktu: {
    title: "GİZ çöktü",
    verdict: "İFŞA",
    win: false,
    body: "Resmi inkâr, fiilî yapının ağırlığını taşıyamadı. Sızıntı basılmadı. Asimetri kamuya aktı. Masa, ‘yok’ diyemez hale geldi.",
  },
  ersever_esigi: {
    title: "Konuşan içerideki",
    verdict: "EŞİK",
    win: false,
    body: "Ersever hattı konuştu ve GİZ zaten inceydi. Kaset, sahanın üzerine oturdu. Bastırma geç kaldı. İçeriden kırılma, dışarıdaki kazadan önce geldi.",
  },
  komuta_felaketi: {
    title: "Komuta kayması",
    verdict: "KAYMA",
    win: false,
    body: "1990 devri saha ile idariyi kopardı. Kapasite ve koruma birlikte düştü. Emir-komuta boşluğu, parçalı ağın üzerine felaket olarak bindi.",
  },
  susurluk_patlama: {
    title: "Görünürlük patlaması",
    verdict: "3 KASIM",
    win: false,
    body: "Kesişim bağları kilitlendi. GİZ yetmedi. Aynı araç, aynı gece, aynı kamuoyu. Parçalı çıkar ağları bir kaza ile tek karede göründü. Masa bunu taşıyamadı.",
  },
  kurumsal_tasfiye: {
    title: "Kurumsal tasfiye",
    verdict: "DAĞIT",
    win: false,
    body: "Masa ağı küçülttü, kalkanı tuttu. Saha boşaldı. Koruma kendi boşluğunu yedi. Tasfiye bir temizlik değil; kapasitesiz inkârdır.",
  },
  rakip_zafer: {
    title: "Rakip hat aldı",
    verdict: "EMİLİM",
    win: false,
    body: "Emniyet–yeraltı kesişimi boşluğu doldurdu. Jandarma masası emir vermedi; yerini kaybetti. Eşgüdüm uydurulmadı — pay kaydı.",
  },
  kismi_adalet: {
    title: "Kısmi görünürlük",
    verdict: "KOMİSYON",
    win: false,
    body: "Kamuoyu ve hukuk ısındı. Bazı bağlar BELGELİ kilitlendi, bazı emirler boşlukta kaldı. Adalet tam değil; dosya açık.",
  },
  saha_felaketi: {
    title: "Saha kendi işini yaptı",
    verdict: "KOPUŞ",
    win: false,
    body: "Sadakat çatladı, kapasite yüksek kaldı. Masa kontrol etmedi; saha freelance yürüdü. Yumuşak başlangıç sert bitti.",
  },
};

export const NPC_LINES = [
  {
    id: "jitem",
    name: "JİTEM / jandarma istihbarat",
    wants: "Saha kapasitesi ve resmi inkâr. Kurumsal görünürlük istemez.",
  },
  {
    id: "mit",
    name: "MİT iç hatları",
    wants: "Kendi kurumunu korumak. Abas hattı mesafe; Eymür hattı belge ve uyarı. JİTEM ile eşgüdüm varsayılmaz.",
  },
  {
    id: "emniyet",
    name: "Emniyet–yeraltı",
    wants: "Çatlı tipi fayda. Jandarma masasının uzantısı değildir. Yükseldikçe GİZ yer.",
  },
  {
    id: "ersever",
    name: "Ersever saha",
    wants: "Sahada kalmak. Komuta kayarsa ve GİZ incelirse konuşur. Kahramanlık aramaz.",
  },
] as const;
