import type { ClaimRecord, RelationRecord, ResearchRecord } from "./schema.ts";
import {
  EXTRA_CLAIMS,
  EXTRA_ORGS,
  EXTRA_PERSONS,
  EXTRA_RELATIONS,
  HISTORY as RAW_HISTORY,
} from "./catalog-extra.ts";
import { hydrateClaim, hydrateHistory, hydrateRelation, hydrateResearch } from "./hydrate.ts";

const unk = (t: string) => ({ kind: "unknown" as const, text: t });
const assume = (t: string) => ({ kind: "gameAssumption" as const, text: t });
const sourced = (t: string) => ({ kind: "sourced" as const, text: t });

export const PERSONS: ResearchRecord[] = [
  {
    id: "per_dogan",
    playId: "dogan",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Arif Doğan",
    realPerson: true,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_dogan", "src_ergenekon"],
    sourceLocation: "Doğan anlatımı; Ergenekon süreci tanıklıkları",
    role: "İdari / kurucu rol iddiası.",
    summary: "‘JİTEM’i ben kurdum’ anlatısı. Saha hattının karşısında idari masa.",
    provenance: {
      historicalFact: "Jandarma istihbarat içinde idari figür olarak kaynaklarda geçer.",
      sourceClaim: "Kendi anlatımında kurucu rol. Ersever saha hattı ile gerilim.",
      gameReconstruction: "Oyunda idari hat başlangıç seçeneğinin yüzü.",
      alternativeOutcome: "Kurucu rol kabul edilmese de idari masa durur; belge boşluğu kapanmaz.",
      contradictions: ["Kuruluş günü belgesi yok (BOŞLUK). Devir detayı TARTIŞMALI."],
    },
    motivation: unk("Kaynaklar niyeti kesinleştirmez. İdari koruma varsayımı oyunsal işaretlenir."),
    relatedIds: ["org_jitem", "per_ersever"],
    relatedActors: ["per_ersever", "per_veli"],
    relatedEvents: ["hist_formation", "hist_command"],
    knownBy: ["jitem", "askeri"],
    discoverability: "early",
    gameUnlock: { appearTurn: 1, bilgi: 0 },
    developerNotes: "İdari hat yüzü. Emir uydurulmaz.",
    appearTurn: 1,
    fiction: false,
  },
  {
    id: "per_ersever",
    playId: "ersever",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Ahmet Cem Ersever",
    realPerson: true,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_ersever", "src_aygan"],
    sourceLocation: "Binbaşı Ersever’in İtirafları; Aygan tanıklığı",
    date: "1993-11",
    role: "Saha hattı. İtirafçı timleri, sivil kıyafet.",
    summary: "1980’ler ortası–1993 saha. 1993 konuşma + ölüm.",
    provenance: {
      historicalFact: "Kasım 1993: Ersever, Nevval Boz ve bir itirafçı öldürüldü. Cesetler BELGELİ.",
      sourceClaim: "Yalçın kasetleri: timler, itirafçılar, sivil kıyafet. Fail Yeşil iddiası çoklu tanıklık.",
      gameReconstruction: "Konuşan içerideki. Giz/bilgi eşiği.",
      alternativeOutcome: "Ölüm çıpası durur. Konuşmanın hasarı, kim korundu, kasetin dolaşımı campaign’e göre değişir.",
      contradictions: ["Emir kaynağı (Küçük/Ankara) TARTIŞMALI. Bu dosyada emir uydurulmaz."],
    },
    motivation: unk("Konuşma gerekçesi kaynaklarda tam kapanmaz. Oyun ‘sızıntı hesabı’ olarak işler."),
    relatedIds: ["org_jitem", "per_aygan", "per_yesil", "per_nevval"],
    relatedActors: ["per_aygan", "per_yesil", "per_nevval", "per_dogan"],
    relatedEvents: ["hist_tapes", "hist_ersever_death"],
    knownBy: ["jitem"],
    discoverability: "early",
    gameUnlock: { appearTurn: 1, bilgi: 0 },
    developerNotes: "Saha hattı. Çıpa ölüm durmaz.",
    appearTurn: 1,
    fiction: false,
  },
  {
    id: "per_veli",
    playId: "veli",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Veli Küçük",
    realPerson: true,
    factionId: "jitem",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_yalcin_ersever", "src_ergenekon"],
    sourceLocation: "Ersever bağlamı; Ergenekon tanıklıkları",
    role: "1990 sonrası komuta hattı iddiası.",
    summary: "Doğan ayrılışı sonrası emir-komuta kayması.",
    provenance: {
      historicalFact: "Jandarma istihbarat içinde adı geçen komuta figürü.",
      sourceClaim: "1990 devri ve Ersever cinayeti emir kaynağı iddiaları.",
      gameReconstruction: "Komuta kayması düğümü. Güçlendirmek ifşa pahalıdır.",
      alternativeOutcome: "Devir iddiası kabul edilmese de 1990 kayması çıpa olarak durur.",
      contradictions: ["Detay TARTIŞMALI. Emir uydurulmaz."],
    },
    motivation: unk("Kaynak dışı psikoloji yazılmaz."),
    relatedIds: ["org_jitem", "per_ersever"],
    relatedActors: ["per_ersever", "per_dogan"],
    relatedEvents: ["hist_command"],
    knownBy: ["jitem"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 4, bilgi: 28 },
    developerNotes: "Emir kaynağı kilitlenmez.",
    appearTurn: 4,
    fiction: false,
  },
  {
    id: "per_abas",
    playId: "abas",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Hiram Abas",
    realPerson: true,
    factionId: "mit",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_pipo", "src_eymur"],
    sourceLocation: "Pipo; Eymür yazıları",
    date: "1990-09-26",
    role: "MİT operatörü. Profesyonel profil.",
    summary: "26 Eylül 1990 İstanbul suikastı.",
    provenance: {
      historicalFact: "Ölüm BELGELİ. Aynı yıl ikinci MİT görevlisi suikastı.",
      sourceClaim: "Takip ekibinin üç gün önce kaldırıldığı anlatılır. Cenazede Eymür ve Eken.",
      gameReconstruction: "MİT profesyonel kanadının kırılması. JİTEM zaferi değildir.",
      alternativeOutcome: "Ölüm durur. JİTEM bağ iddiası her campaign’de kilitlenmez.",
      contradictions: ["Fail ve emir zinciri TARTIŞMALI. JİTEM’e zorla bağlama TARTIŞMALI."],
    },
    motivation: sourced("Kurumsal/profesyonel hat — Pipo profili. JİTEM sözcüsü değil."),
    relatedIds: ["org_mit", "per_eymur", "per_eken"],
    relatedActors: ["per_eymur", "per_eken"],
    relatedEvents: ["hist_abas"],
    knownBy: ["mit"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 3, bilgi: 18 },
    developerNotes: "JİTEM zaferi yazılmaz.",
    appearTurn: 3,
    fiction: false,
  },
  {
    id: "per_eymur",
    playId: "eymur",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Mehmet Eymür",
    realPerson: true,
    factionId: "mit",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_eymur", "src_yalcin_pipo"],
    sourceLocation: "Eymür yazıları / atin.org; Pipo",
    role: "MİT Kontrterör. İçeriden uyarı yazan hat.",
    summary: "Raporları asimetri üretir. JİTEM’in sözcüsü değildir.",
    provenance: {
      historicalFact: "MİT içinde kontrterör hattı. Yazılı uyarılar arşivde.",
      sourceClaim: "Emniyet–yeraltı kesişimine ve JİTEM’e dair uyarılar.",
      gameReconstruction: "Bilgi barını yükseltir, giz’i inceltebilir. Bağımsız NPC.",
      alternativeOutcome: "Uyarı gecikirse masa bilmez; MİT kendi dosyasıyla yürür.",
      contradictions: ["Eymür–Abas gerilimi kurum içidir; jandarmaya otomatik bağlanmaz."],
    },
    motivation: sourced("Kendi kurumunu korumak ve belgelemek — yazılarından."),
    relatedIds: ["org_mit", "per_abas", "org_emniyet"],
    relatedActors: ["per_abas", "per_eken"],
    relatedEvents: ["hist_abas"],
    knownBy: ["mit"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 3, bilgi: 16 },
    developerNotes: "Bağımsız bilgi üretici.",
    appearTurn: 3,
    fiction: false,
  },
  {
    id: "per_eken",
    playId: "eken",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Korkut Eken",
    realPerson: true,
    factionId: "mit",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_pipo", "src_eymur"],
    sourceLocation: "Pipo; Eymür",
    role: "Özel tim / istihbarat kesişimi.",
    summary: "Abas ve Eymür ile kaynaklarda geçer.",
    provenance: {
      historicalFact: "İstihbarat–özel tim kesişiminde adı geçer.",
      sourceClaim: "Emniyet özel tim hattına yakın durur.",
      gameReconstruction: "JİTEM komuta zincirine yedirilmez.",
      contradictions: [],
    },
    motivation: unk("Kaynaklar niyeti kapatmaz."),
    relatedIds: ["org_mit", "per_abas"],
    relatedActors: ["per_abas", "per_eymur"],
    relatedEvents: ["hist_abas"],
    knownBy: ["mit", "emniyet"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 5, bilgi: 30 },
    appearTurn: 5,
    fiction: false,
  },
  {
    id: "per_yesil",
    playId: "yesil",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Mahmut Yıldırım (Yeşil)",
    realPerson: true,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_pekmezci", "src_aygan", "src_yalcin_ersever"],
    sourceLocation: "Pekmezci; Aygan; Ersever bağlamı",
    role: "Operatif / tetikçi profili. Kendi başına karar verici değil.",
    summary: "Ersever cinayeti fail iddiası GÜÇLÜ. Emir TARTIŞMALI.",
    provenance: {
      historicalFact: "Kaynaklarda operatif olarak geçer.",
      sourceClaim: "Ersever cinayeti faili — çoklu tanıklık.",
      gameReconstruction: "Saha kapasitesini şişirir, giz yakar. Harcamak ısıtır.",
      alternativeOutcome: "Fail iddiası her campaign’de aynı kamuoyuna düşmez. Emir boşluğu durur.",
      contradictions: ["Emir kaynağı TARTIŞMALI."],
    },
    motivation: assume("Oyun: saha aracı. Tarihsel ‘ne istiyordu’ yazılmaz."),
    relatedIds: ["per_ersever", "org_jitem"],
    relatedActors: ["per_ersever", "per_aygan"],
    relatedEvents: ["hist_ersever_death"],
    knownBy: ["jitem"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 2, bilgi: 24 },
    developerNotes: "Kendi başına karar verici değil.",
    appearTurn: 2,
    fiction: false,
  },
  {
    id: "per_aygan",
    playId: "aygan",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Abdülkadir Aygan",
    realPerson: true,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_aygan"],
    sourceLocation: "Aygan tanıklığı",
    role: "İtirafçı tim. Sonradan tanık.",
    summary: "Ersever saha hattının itirafçı katmanı.",
    provenance: {
      historicalFact: "İtirafçı/tanık olarak kayıtlarda.",
      sourceClaim: "Tim katmanı ve iç işleyiş tanıklığı.",
      gameReconstruction: "Kapasite artırır; konuşursa bilgi patlar.",
      alternativeOutcome: "Korunursa konuşma gecikir; harcanırsa tanıklık ısınır.",
      contradictions: [],
    },
    motivation: unk("Sonradan tanıklık ile saha dönemi aynı niyet değildir."),
    relatedIds: ["per_ersever"],
    relatedActors: ["per_ersever"],
    relatedEvents: ["hist_formation"],
    knownBy: ["jitem"],
    discoverability: "early",
    gameUnlock: { appearTurn: 2, bilgi: 12 },
    appearTurn: 2,
    fiction: false,
  },
  {
    id: "per_catli",
    playId: "catli",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Abdullah Çatlı",
    realPerson: true,
    factionId: "emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_reis", "src_susurluk_kaza"],
    sourceLocation: "Reis; Susurluk kamu kaydı",
    date: "1996-11-03",
    role: "Ülkücü geçmiş, sahte kimlik, devlet–mafya kesişimi.",
    summary: "JİTEM uzantısı değil. 1993–96 Emniyet–yeraltı yükselişi.",
    provenance: {
      historicalFact: "3 Kasım 1996 Susurluk kazasında öldü. Kimlikler BELGELİ.",
      sourceClaim: "Özel tim / yeraltı kesişimi. Eymür uyarıları.",
      gameReconstruction: "Ayrı çıkar ağı. Eşgüdüm varsayımı TARTIŞMALI.",
      alternativeOutcome: "Kaza çıpası durur. Kesişimin ısınması soğutulabilir.",
      contradictions: ["JİTEM emir-komuta uzantısı değildir."],
    },
    motivation: assume("Oyun: fayda ve koruma. İç dünya kaynak dışı bırakılır."),
    relatedIds: ["org_emniyet", "per_kocadag", "per_bucak", "per_gonca"],
    relatedActors: ["per_kocadag", "per_bucak", "per_gonca", "per_agar"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["emniyet", "yeralti"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 40 },
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "per_kocadag",
    playId: "kocadag",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Hüseyin Kocadağ",
    realPerson: true,
    factionId: "emniyet",
    evidence: "BELGELİ",
    sourceIds: ["src_susurluk_kaza"],
    sourceLocation: "Susurluk kazası kamu kaydı",
    date: "1996-11-03",
    role: "Emniyet. Susurluk aracındaki resmi yüz.",
    summary: "Çatlı ile aynı araç.",
    provenance: {
      historicalFact: "Kazada ölüm BELGELİ.",
      sourceClaim: "Operasyonel ortaklık kazada kilitlenir.",
      gameReconstruction: "Resmi yüz. Öncesi GÜÇLÜ, kaza BELGELİ.",
      contradictions: [],
    },
    motivation: unk("Niyet kapanmaz."),
    relatedIds: ["org_emniyet", "per_catli"],
    relatedActors: ["per_catli"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["emniyet"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 42 },
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "per_bucak",
    playId: "bucak",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Sedat Bucak",
    realPerson: true,
    factionId: "siyaset",
    evidence: "BELGELİ",
    sourceIds: ["src_susurluk_kaza", "src_tbmm_susurluk"],
    sourceLocation: "Susurluk kazası; TBMM komisyonu",
    role: "Milletvekili / aşiret. Siyasi koridor.",
    summary: "Aynı araçta. Siyaset–yeraltı görünür halkası.",
    provenance: {
      historicalFact: "Kazadan sağ çıktı. Araçtaki varlığı BELGELİ.",
      sourceClaim: "Koruma ve bölgesel güç kesişimi.",
      gameReconstruction: "Koruma hem taşır hem yakar.",
      contradictions: [],
    },
    motivation: unk("Siyasi hesap kaynak dışı doldurulmaz."),
    relatedIds: ["per_catli"],
    relatedActors: ["per_catli", "per_kocadag"],
    relatedEvents: ["hist_susurluk", "hist_commission"],
    knownBy: ["siyaset", "emniyet"],
    discoverability: "late",
    gameUnlock: { appearTurn: 9, bilgi: 48 },
    appearTurn: 9,
    fiction: false,
  },
  {
    id: "per_gonca",
    playId: "gonca",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Gonca Us",
    realPerson: true,
    factionId: "yeralti",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_susurluk_kaza"],
    sourceLocation: "Susurluk kazası kamu kaydı",
    date: "1996-11-03",
    role: "Çatlı’nın yanında. Susurluk’ta birlikte.",
    summary: "İlişki kısa. Birlikte ölüm GÜÇLÜ.",
    provenance: {
      historicalFact: "Kazada ölüm. Araçtaki varlığı kamu kaydı.",
      sourceClaim: "Kişisel/fayda ilişkisi ≈1 yıl.",
      gameReconstruction: "Ağın sivil görünürlük maliyeti.",
      contradictions: ["Kişisel detay sınırlıdır."],
    },
    motivation: unk("Özel hayat spekülasyonu yok."),
    relatedIds: ["per_catli"],
    relatedActors: ["per_catli"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["yeralti"],
    discoverability: "late",
    gameUnlock: { appearTurn: 9, bilgi: 50 },
    appearTurn: 9,
    fiction: false,
  },
  {
    id: "per_mumcu",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Uğur Mumcu",
    realPerson: true,
    factionId: "media",
    evidence: "BELGELİ",
    sourceIds: ["src_mumcu"],
    sourceLocation: "haber arşivi / kamu kaydı",
    date: "1993-01-24",
    role: "Gazeteci. Araştırma hattı.",
    summary: "24 Ocak 1993 suikastı BELGELİ. JİTEM bağ TARTIŞMALI.",
    provenance: {
      historicalFact: "Ankara’da bomba ile öldürüldü. Kamu kaydı.",
      sourceClaim: "Derin yapı / kontrgerilla araştırma hattı.",
      gameReconstruction: "Medya tarafının bilgi ve kamuoyu üreticisi. Haritada zorunlu düğüm değil.",
      contradictions: ["Fail ve emir TARTIŞMALI. JİTEM’e zorla bağlama yok."],
    },
    motivation: sourced("Haber ve arşiv — kamuya açık meslek."),
    relatedIds: ["org_media"],
    relatedEvents: ["hist_mumcu"],
    knownBy: ["media"],
    discoverability: "mid",
    fiction: false,
  },
  {
    id: "per_nevval",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Nevval Boz",
    realPerson: true,
    factionId: "jitem",
    evidence: "BELGELİ",
    sourceIds: ["src_yalcin_ersever"],
    sourceLocation: "Binbaşı Ersever’in İtirafları / kamu kaydı",
    date: "1993-11",
    role: "Ersever ile birlikte öldürüldü.",
    summary: "Ceset BELGELİ. Operatif komuta yok.",
    provenance: {
      historicalFact: "Kasım 1993 ölüm.",
      sourceClaim: "Ersever ile birlikte.",
      gameReconstruction: "Saha hattı kapanışının sivil maliyeti. Emir uydurulmaz.",
      contradictions: [],
    },
    motivation: unk("Kaynak dışı iç dünya yok."),
    relatedIds: ["per_ersever"],
    relatedActors: ["per_ersever"],
    relatedEvents: ["hist_ersever_death"],
    knownBy: ["jitem"],
    discoverability: "mid",
    fiction: false,
  },
  {
    id: "per_yalcin",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Soner Yalçın",
    realPerson: true,
    factionId: "media",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_ersever", "src_yalcin_pipo", "src_yalcin_reis"],
    sourceLocation: "yayımlanmış kitaplar",
    role: "Gazeteci / kitap hattı.",
    summary: "Ersever kasetleri, Pipo, Reis. Kaynak, fail değil.",
    provenance: {
      historicalFact: "Yayımlanmış kitaplar ve röportajlar.",
      sourceClaim: "Saha ve MİT anlatılarını kamuya taşıdı.",
      gameReconstruction: "Medya NPC’si bilgi üretir, giz yakar.",
      contradictions: ["Anlatı tek kanıt değildir; kanıt seviyesi ayrı tutulur."],
    },
    motivation: sourced("Yayın ve araştırma — kamuya açık meslek."),
    relatedIds: ["per_ersever", "org_media"],
    knownBy: ["media"],
    discoverability: "mid",
    fiction: false,
  },
];

export const ORGS: ResearchRecord[] = [
  {
    id: "org_jitem",
    playId: "jitem",
    kind: "org",
    nodeKind: "kurum",
    displayName: "JİTEM",
    realPerson: false,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_dogan", "src_yalcin_ersever", "src_aygan"],
    sourceLocation: "Doğan; Ersever; Aygan",
    date: "1986–88",
    role: "Jandarma istihbarat grup ve timleri. Fiilî yapı.",
    summary: "Resmi dil uzun yıllar ‘yok’ der. Fiilî varlık GÜÇLÜ.",
    provenance: {
      historicalFact: "Resmi inkâr kamu dilinde vardır. Fiilî tim/itirafçı anlatıları çoklu kaynaktır.",
      sourceClaim: "1986–88 civarı oluşum. Doğan kurucu iddiası.",
      gameReconstruction: "Oyuncunun saha masası bu düğüm etrafında döner. Tek merkezli komplo üretilmez.",
      contradictions: ["Kesin kuruluş belgesi BOŞLUK. Siyasi zirve onayı BOŞLUK."],
    },
    motivation: assume("Oyun: saha kapasitesi + resmi inkâr. Kurumsal ‘irade’ yazılmaz."),
    relatedIds: ["per_dogan", "per_ersever"],
    relatedEvents: ["hist_formation"],
    knownBy: ["jitem", "askeri"],
    discoverability: "early",
    gameUnlock: { appearTurn: 1, bilgi: 0 },
    appearTurn: 1,
    fiction: false,
  },
  {
    id: "org_mit",
    playId: "mit",
    kind: "org",
    nodeKind: "kurum",
    displayName: "MİT",
    realPerson: false,
    factionId: "mit",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_pipo", "src_eymur"],
    sourceLocation: "Pipo; Eymür yazıları",
    role: "Milli İstihbarat. İç hatlar homojen değil.",
    summary: "Abas–Eymür–Eken tek ses değildir.",
    provenance: {
      historicalFact: "Kurum kamu kurumudur. İç hat gerilimi kaynaklıdır.",
      sourceClaim: "JİTEM ile sürekli eşgüdüm varsayılmaz.",
      gameReconstruction: "Bağımsız NPC. Kendi bilgi haritası var.",
      contradictions: ["Tek yürek MİT modeli kaynaklarla uyumsuz."],
    },
    motivation: sourced("Kendi kurumunu korumak — Eymür/Pipo hattı."),
    relatedIds: ["per_abas", "per_eymur"],
    knownBy: ["mit"],
    discoverability: "mid",
    gameUnlock: { appearTurn: 3, bilgi: 18 },
    appearTurn: 3,
    fiction: false,
  },
  {
    id: "org_emniyet",
    playId: "emniyet",
    kind: "org",
    nodeKind: "kurum",
    displayName: "Emniyet",
    realPerson: false,
    factionId: "emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_eymur", "src_yalcin_reis", "src_susurluk_kaza"],
    sourceLocation: "Eymür; Reis; Susurluk",
    role: "Polis özel tim / yeraltı kesişimi.",
    summary: "JİTEM’den ayrı çıkar ağı. 1993 sonrası ısınır.",
    provenance: {
      historicalFact: "Kamu kurumu. Susurluk’ta resmi yüz (Kocadağ) BELGELİ.",
      sourceClaim: "Çatlı yükselişi bu koridorda.",
      gameReconstruction: "Jandarma hattını emretmez.",
      contradictions: ["Eşgüdüm TARTIŞMALI."],
    },
    motivation: assume("Oyun: kendi operasyonel payı. Tek el yok."),
    relatedIds: ["per_catli", "per_kocadag"],
    knownBy: ["emniyet"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 36 },
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "org_guneydogu",
    playId: "guneydogu",
    kind: "place",
    nodeKind: "koridor",
    displayName: "Güneydoğu saha",
    realPerson: false,
    factionId: "jitem",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_dogan", "src_yalcin_ersever"],
    sourceLocation: "Doğan; Ersever",
    role: "Koridor. Tim, itirafçı, sivil kıyafet.",
    summary: "Yapı burada fiilen doğar.",
    provenance: {
      historicalFact: "Bölgede silahlı çatışma ortamı kamu tarihidir.",
      sourceClaim: "JİTEM fiilî doğuş zemini.",
      gameReconstruction: "Ankara’nın bildiği ile sahanın yaptığı aynı değildir.",
      contradictions: [],
    },
    motivation: unk("Coğrafya niyet taşımaz."),
    relatedIds: ["org_jitem"],
    knownBy: ["jitem"],
    discoverability: "early",
    gameUnlock: { appearTurn: 1, bilgi: 0 },
    appearTurn: 1,
    fiction: false,
  },
  {
    id: "org_tbmm",
    playId: "tbmm",
    kind: "org",
    nodeKind: "kurum",
    displayName: "TBMM komisyonu",
    realPerson: false,
    factionId: "hukuk",
    evidence: "BELGELİ",
    sourceIds: ["src_tbmm_susurluk"],
    sourceLocation: "TBMM tutanakları",
    date: "1996–97",
    role: "Meclis soruşturması. Kamuoyu ve hukuk yüzeyi.",
    summary: "Susurluk sonrası parçalı itiraf.",
    provenance: {
      historicalFact: "Komisyon kuruldu. Tutanaklar kamu.",
      sourceClaim: "İnkâr, parçalı kabul, siyasi idare.",
      gameReconstruction: "Hukuk ve kamuoyu barlarını işler. Tek doğru komplo çözmez.",
      contradictions: [],
    },
    motivation: sourced("Anayasal denetim — kamu işlevi."),
    relatedIds: ["org_emniyet"],
    relatedEvents: ["hist_commission"],
    knownBy: ["hukuk", "siyaset"],
    discoverability: "late",
    gameUnlock: { appearTurn: 10, bilgi: 0 },
    appearTurn: 10,
    fiction: false,
  },
  {
    id: "org_media",
    kind: "org",
    nodeKind: "kurum",
    displayName: "Basın / araştırma hattı",
    realPerson: false,
    factionId: "media",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_mumcu", "src_yalcin_ersever"],
    sourceLocation: "haber ve kitap hattı",
    role: "Haber, kitap, sızıntı yüzeyi.",
    summary: "Asimetrik bilgi: çoğu zaman yanlış veya eksik bilir.",
    provenance: {
      historicalFact: "Yayımlanmış haber ve kitaplar.",
      sourceClaim: "Derin yapı iddiaları kanıt seviyesine göre değişir.",
      gameReconstruction: "Medya NPC’si oyuncunun bildiğini otomatik bilmez.",
      contradictions: [],
    },
    motivation: sourced("Haber rekabeti — meslek."),
    relatedIds: ["per_mumcu", "per_yalcin"],
    knownBy: ["media"],
    discoverability: "mid",
    fiction: false,
  },
];

export const CLAIMS: ClaimRecord[] = [
  {
    id: "clm_jitem_exists",
    title: "JİTEM fiilî varlık",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_dogan", "src_yalcin_ersever", "src_aygan"],
    sourceLocation: "Doğan; Ersever; Aygan",
    aboutIds: ["org_jitem"],
    layer: "sourceClaim",
    statement: "Jandarma istihbarat içinde fiilî tim/itirafçı yapı çalışmıştır.",
    contradiction: "Resmi dil uzun yıllar yok demiştir (inkâr BELGELİ).",
    knownBy: ["jitem", "askeri"],
    worldStatus: "TRUE",
    fiction: false,
  },
  {
    id: "clm_jitem_founding_date",
    title: "Kesin kuruluş günü",
    evidence: "BOŞLUK",
    sourceIds: ["src_dogan"],
    sourceLocation: "Doğan anlatımı",
    aboutIds: ["org_jitem"],
    layer: "historicalFact",
    statement: "Kaynaklar kesin bir kuruluş belgesi göstermez.",
    contradiction: "Doğan anlatısı tarih verir; belge boşluğu durur.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_yesil_ersever",
    title: "Ersever cinayeti faili Yeşil",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_pekmezci", "src_aygan", "src_yalcin_ersever"],
    sourceLocation: "Pekmezci; Aygan; Ersever",
    aboutIds: ["per_yesil", "per_ersever"],
    layer: "sourceClaim",
    statement: "Çoklu tanıklık Yeşil’i fail olarak gösterir.",
    contradiction: "Emir kaynağı TARTIŞMALI bırakılır.",
    worldStatus: "PARTIAL",
    fiction: false,
  },
  {
    id: "clm_veli_order",
    title: "Ersever cinayeti emir kaynağı",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_yalcin_ersever", "src_ergenekon"],
    sourceLocation: "Ersever bağlamı; Ergenekon",
    aboutIds: ["per_veli", "per_ersever"],
    layer: "sourceClaim",
    statement: "Ankara / Küçük hattı emir iddiası vardır.",
    contradiction: "Bu dosyada emir uydurulmaz ve kilitlenmez.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_abas_jitem",
    title: "Abas suikastının JİTEM’e bağlanması",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_yalcin_pipo"],
    sourceLocation: "Pipo",
    aboutIds: ["per_abas", "org_jitem"],
    layer: "sourceClaim",
    statement: "Zorla bağlama iddiaları dolaşır.",
    contradiction: "Fail/emir boşluğu durur. Oyun bağ üretmez.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_susurluk_car",
    title: "Susurluk aynı araç",
    evidence: "BELGELİ",
    sourceIds: ["src_susurluk_kaza", "src_tbmm_susurluk"],
    sourceLocation: "kaza kaydı; TBMM",
    aboutIds: ["per_catli", "per_kocadag", "per_bucak", "per_gonca"],
    layer: "historicalFact",
    statement: "3 Kasım 1996 aynı Mercedes. Kimlik, silah, belge.",
    contradiction: null,
    worldStatus: "TRUE",
    fiction: false,
  },
  {
    id: "clm_jitem_catli_command",
    title: "Çatlı JİTEM uzantısıdır",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_yalcin_reis", "src_eymur"],
    sourceLocation: "Reis; Eymür",
    aboutIds: ["per_catli", "org_jitem"],
    layer: "sourceClaim",
    statement: "Tek el komplo anlatısı Çatlı’yı jandarma hattına yedirir.",
    contradiction: "Eymür/Reis hattı ayrı çıkar ağına işaret eder. Oyun eşgüdüm uydurmaz.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_mumcu_jitem",
    title: "Mumcu suikastı JİTEM emri",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_mumcu"],
    sourceLocation: "Mumcu arşivi / sonraki iddialar",
    aboutIds: ["per_mumcu", "org_jitem"],
    layer: "sourceClaim",
    statement: "Fail/emir üzerine iddialar vardır.",
    contradiction: "Ölüm BELGELİ, bağ TARTIŞMALI. Oyun bağ kilitlemez.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
];

export const RELATIONS: RelationRecord[] = [
  { id: "rel_dogan_ersever", playId: "dogan-ersever", fromPlayId: "dogan", toPlayId: "ersever", label: "idari / saha", evidence: "GÜÇLÜ", sourceIds: ["src_dogan", "src_yalcin_ersever"], sourceLocation: "Doğan + Ersever", layer: "sourceClaim", appearTurn: 1 },
  { id: "rel_dogan_jitem", playId: "dogan-jitem", fromPlayId: "dogan", toPlayId: "jitem", label: "kurucu iddiası", evidence: "GÜÇLÜ", sourceIds: ["src_dogan"], sourceLocation: "Doğan anlatımı", layer: "sourceClaim", appearTurn: 1 },
  { id: "rel_ersever_jitem", playId: "ersever-jitem", fromPlayId: "ersever", toPlayId: "jitem", label: "saha hattı", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_ersever"], sourceLocation: "Ersever", layer: "sourceClaim", appearTurn: 1 },
  { id: "rel_ersever_guneydogu", playId: "ersever-guneydogu", fromPlayId: "ersever", toPlayId: "guneydogu", label: "operatif koridor", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_ersever"], sourceLocation: "Ersever", layer: "sourceClaim", appearTurn: 1 },
  { id: "rel_jitem_guneydogu", playId: "jitem-guneydogu", fromPlayId: "jitem", toPlayId: "guneydogu", label: "fiilî zemin", evidence: "GÜÇLÜ", sourceIds: ["src_dogan", "src_yalcin_ersever"], sourceLocation: "Doğan; Ersever", layer: "sourceClaim", appearTurn: 1 },
  { id: "rel_ersever_aygan", playId: "ersever-aygan", fromPlayId: "ersever", toPlayId: "aygan", label: "itirafçı tim", evidence: "GÜÇLÜ", sourceIds: ["src_aygan"], sourceLocation: "Aygan tanıklığı", layer: "sourceClaim", appearTurn: 2 },
  { id: "rel_ersever_yesil", playId: "ersever-yesil", fromPlayId: "ersever", toPlayId: "yesil", label: "operatif", evidence: "GÜÇLÜ", sourceIds: ["src_aygan", "src_pekmezci"], sourceLocation: "Aygan; Pekmezci", layer: "sourceClaim", appearTurn: 2 },
  { id: "rel_abas_eymur", playId: "abas-eymur", fromPlayId: "abas", toPlayId: "eymur", label: "MİT içi", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_pipo", "src_eymur"], sourceLocation: "Pipo; Eymür", layer: "sourceClaim", appearTurn: 3 },
  { id: "rel_abas_mit", playId: "abas-mit", fromPlayId: "abas", toPlayId: "mit", label: "operatör", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_pipo"], sourceLocation: "Pipo", layer: "historicalFact", appearTurn: 3 },
  { id: "rel_eymur_mit", playId: "eymur-mit", fromPlayId: "eymur", toPlayId: "mit", label: "kontrterör", evidence: "GÜÇLÜ", sourceIds: ["src_eymur"], sourceLocation: "Eymür yazıları", layer: "historicalFact", appearTurn: 3 },
  { id: "rel_ersever_veli", playId: "ersever-veli", fromPlayId: "ersever", toPlayId: "veli", label: "1990 komuta", evidence: "TARTIŞMALI", sourceIds: ["src_yalcin_ersever"], sourceLocation: "Ersever bağlamı", layer: "sourceClaim", appearTurn: 4, breakIf: "commandShifted" },
  { id: "rel_veli_jitem", playId: "veli-jitem", fromPlayId: "veli", toPlayId: "jitem", label: "devir iddiası", evidence: "TARTIŞMALI", sourceIds: ["src_ergenekon"], sourceLocation: "Ergenekon tanıklıkları", layer: "sourceClaim", appearTurn: 4 },
  { id: "rel_abas_eken", playId: "abas-eken", fromPlayId: "abas", toPlayId: "eken", label: "MİT / özel", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_pipo"], sourceLocation: "Pipo", layer: "sourceClaim", appearTurn: 5 },
  { id: "rel_eken_mit", playId: "eken-mit", fromPlayId: "eken", toPlayId: "mit", label: "özel tim kesişimi", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_pipo", "src_eymur"], sourceLocation: "Pipo; Eymür", layer: "sourceClaim", appearTurn: 5 },
  { id: "rel_eymur_emniyet", playId: "eymur-emniyet", fromPlayId: "eymur", toPlayId: "emniyet", label: "uyarı / kesişim", evidence: "GÜÇLÜ", sourceIds: ["src_eymur"], sourceLocation: "Eymür raporları", layer: "sourceClaim", appearTurn: 8 },
  { id: "rel_catli_emniyet", playId: "catli-emniyet", fromPlayId: "catli", toPlayId: "emniyet", label: "özel tim hattı", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_reis", "src_eymur"], sourceLocation: "Reis; Eymür", layer: "sourceClaim", appearTurn: 8 },
  { id: "rel_catli_kocadag", playId: "catli-kocadag", fromPlayId: "catli", toPlayId: "kocadag", label: "operasyonel ortak", evidence: "BELGELİ", sourceIds: ["src_susurluk_kaza"], sourceLocation: "Susurluk kazası", layer: "historicalFact", appearTurn: 8, belgelıLockTurn: 10 },
  { id: "rel_kocadag_emniyet", playId: "kocadag-emniyet", fromPlayId: "kocadag", toPlayId: "emniyet", label: "kurum içi", evidence: "BELGELİ", sourceIds: ["src_susurluk_kaza"], sourceLocation: "Susurluk", layer: "historicalFact", appearTurn: 8 },
  { id: "rel_catli_bucak", playId: "catli-bucak", fromPlayId: "catli", toPlayId: "bucak", label: "kesişim", evidence: "BELGELİ", sourceIds: ["src_susurluk_kaza"], sourceLocation: "Susurluk kazası", layer: "historicalFact", appearTurn: 9, belgelıLockTurn: 10 },
  { id: "rel_catli_gonca", playId: "catli-gonca", fromPlayId: "catli", toPlayId: "gonca", label: "kişisel / fayda", evidence: "GÜÇLÜ", sourceIds: ["src_susurluk_kaza"], sourceLocation: "Susurluk", layer: "sourceClaim", appearTurn: 9, belgelıLockTurn: 10 },
];

const RAW_RESEARCH: ResearchRecord[] = [...PERSONS, ...ORGS, ...EXTRA_PERSONS, ...EXTRA_ORGS];
const RAW_CLAIMS: ClaimRecord[] = [...CLAIMS, ...EXTRA_CLAIMS];
const RAW_RELATIONS: RelationRecord[] = [...RELATIONS, ...EXTRA_RELATIONS];

export const ALL_RESEARCH: ResearchRecord[] = RAW_RESEARCH.map(hydrateResearch);
export const ALL_CLAIMS: ClaimRecord[] = RAW_CLAIMS.map(hydrateClaim);
export const ALL_RELATIONS: RelationRecord[] = RAW_RELATIONS.map(hydrateRelation);
export const HISTORY = RAW_HISTORY.map(hydrateHistory);
export const RESEARCH_BY_PLAY = Object.fromEntries(
  ALL_RESEARCH.filter((r) => r.playId).map((r) => [r.playId as string, r]),
);
