import type { ClaimRecord, HistoryRecord, RelationRecord, ResearchRecord } from "./schema.ts";

const unk = (t: string) => ({ kind: "unknown" as const, text: t });
const assume = (t: string) => ({ kind: "gameAssumption" as const, text: t });
const sourced = (t: string) => ({ kind: "sourced" as const, text: t });

export const EXTRA_PERSONS: ResearchRecord[] = [
  {
    id: "per_agar",
    playId: "agar",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Mehmet Ağar",
    realPerson: true,
    factionId: "siyaset",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk", "src_yalcin_reis"],
    sourceLocation: "TBMM Susurluk tutanakları; Reis bağlamı",
    role: "Emniyet / siyaset koridoru. Susurluk sonrası kamu yüzü.",
    summary: "Polis-siyaset kesişimi. JİTEM komuta zincirine yedirilmez.",
    provenance: {
      historicalFact: "Emniyet ve siyaset kamusal görevler. Susurluk döneminde adı geçer.",
      sourceClaim: "Çatlı hattı ile kesişim iddiaları komisyon ve basında.",
      gameReconstruction: "Siyasi kalkan düğümü. Emretmez; örtü sağlar veya çeker.",
      contradictions: ["Operasyonel emir zinciri TARTIŞMALI. Tek el yok."],
    },
    motivation: unk("Kaynaklar niyeti kapatmaz. Siyasi hesap oyunsal varsayılmaz."),
    relatedIds: ["org_emniyet", "per_catli", "per_sahin"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["siyaset", "emniyet"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 38 },
    developerNotes: "Haritada geç açılır. Çatlı’ya BELGELİ komuta bağlama.",
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "per_sahin",
    playId: "sahin",
    kind: "person",
    nodeKind: "kisi",
    displayName: "İbrahim Şahin",
    realPerson: true,
    factionId: "emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk", "src_yalcin_reis"],
    sourceLocation: "TBMM tutanakları / özel tim hattı",
    role: "Özel harekât. Emniyet saha yüzü.",
    summary: "Jandarma JİTEM’i değildir. Aynı dönemde ayrı hat.",
    provenance: {
      historicalFact: "Emniyet özel harekât kadrosunda adı kamu kaydında geçer.",
      sourceClaim: "Susurluk kesişimi ve özel tim anlatıları.",
      gameReconstruction: "Emniyet kapasitesi. JİTEM uzantısı olarak kilitlenmez.",
      contradictions: ["JİTEM emir-komuta iddiası TARTIŞMALI / yok."],
    },
    motivation: unk("Kaynak dışı psikoloji yok."),
    relatedIds: ["org_ozel_harekat", "per_catli"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["emniyet"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 40 },
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "per_carkin",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Ayhan Çarkın",
    realPerson: true,
    factionId: "emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_carkin"],
    sourceLocation: "tanıklık / basın röportaj hattı",
    role: "Özel tim tanığı. Geç dönem konuşma.",
    summary: "Emniyet özel tim anlatısı. JİTEM dosyasına yedirilmez.",
    provenance: {
      historicalFact: "Emniyet kadrosunda görev. Sonradan tanıklık kamuoyuna yansıdı.",
      sourceClaim: "Özel tim operasyon anlatıları.",
      gameReconstruction: "Araştırma kaydı. Haritada zorunlu düğüm değil.",
      contradictions: ["Tarih ve emir detayı tanıklığa bağlı; BELGELİ kilit yok."],
    },
    motivation: unk("Tanıklık niyeti kapanmaz."),
    relatedIds: ["org_ozel_harekat"],
    discoverability: "hidden",
    fiction: false,
  },
  {
    id: "per_hanefi",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Hanefi Avcı",
    realPerson: true,
    factionId: "emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_hanefi"],
    sourceLocation: "anlatı / kitap hattı",
    role: "Emniyet içi anlatı. Geç dönem.",
    summary: "Kurum içi gerilim kaynağı. 1986–96 omurgasına zorla bağlanmaz.",
    provenance: {
      historicalFact: "Emniyet mensubu. Yayımlanmış anlatı.",
      sourceClaim: "İstihbarat-emniyet kesişimi ve iç hesaplar.",
      gameReconstruction: "Kaynak katmanı. Oyun düğümü değil.",
      contradictions: ["Geriye dönük anlatı; çağdaş belge ile karıştırılmaz."],
    },
    motivation: sourced("Yayımlanmış meslek anlatısı."),
    relatedIds: ["org_emniyet"],
    discoverability: "hidden",
    fiction: false,
  },
  {
    id: "per_ciller",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Tansu Çiller",
    realPerson: true,
    factionId: "siyaset",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk"],
    sourceLocation: "kamu görev / komisyon bağlamı",
    role: "Siyasi koruma hattının kamu ucu.",
    summary: "Başbakanlık dönemi kamu tarihidir. Operatif emir uydurulmaz.",
    provenance: {
      historicalFact: "1993–96 başbakan. Kamu kaydı.",
      sourceClaim: "Susurluk sonrası siyasi sorumluluk tartışması.",
      gameReconstruction: "Siyaset faction’ının gölge ucu. Haritada yok.",
      contradictions: ["Kişisel emir / bilgi derecesi TARTIŞMALI. BOŞLUK durur."],
    },
    motivation: unk("Siyasi niyet kaynak dışı doldurulmaz."),
    relatedIds: ["per_agar"],
    relatedEvents: ["hist_susurluk"],
    discoverability: "late",
    fiction: false,
  },
  {
    id: "per_kutlu",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Kutlu Savaş",
    realPerson: true,
    factionId: "hukuk",
    evidence: "BELGELİ",
    sourceIds: ["src_kutlu_savas"],
    sourceLocation: "Başbakanlık teftiş / Susurluk raporu hattı",
    role: "Resmi rapor yüzü.",
    summary: "Kamu raporu. Tek doğru komplo çözmez.",
    provenance: {
      historicalFact: "Resmi teftiş/rapor süreci kamu kaydıdır.",
      sourceClaim: "Parçalı tespit, inkâr ve boşluk bir arada.",
      gameReconstruction: "Hukuk faction bilgi üreticisi.",
      contradictions: [],
    },
    motivation: sourced("Resmi görev — kamu işlevi."),
    relatedIds: ["org_tbmm"],
    relatedEvents: ["hist_susurluk"],
    discoverability: "late",
    fiction: false,
  },
  {
    id: "per_bitlis",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Eşref Bitlis",
    realPerson: true,
    factionId: "askeri",
    evidence: "BELGELİ",
    sourceIds: ["src_bitlis_kaza", "src_jandarma_kamu"],
    sourceLocation: "kamu kaydı / basın — 17 Şubat 1993",
    date: "1993-02-17",
    role: "Jandarma Genel Komutanı. Kamu görev.",
    summary: "Uçak kazasında ölüm BELGELİ. Sabotaj ve JİTEM bağ iddiaları TARTIŞMALI.",
    provenance: {
      historicalFact: "17 Şubat 1993’te uçak kazasında öldü. Kamu kaydı.",
      sourceClaim: "Sabotaj ve derin yapı bağ iddiaları basında ve sonraki anlatılarda dolaşır.",
      gameReconstruction: "Araştırma kaydı. Haritada zorunlu düğüm değil. Emir/bağ kilidi yok.",
      alternativeOutcome: "Ölüm çıpası durur. Bağ iddiası her campaign’de açılmaz.",
      contradictions: ["Kazanın nedeni TARTIŞMALI. JİTEM emri uydurulmaz."],
    },
    motivation: unk("Kaynaklar niyeti kapatmaz. Oyun iç dünya yazmaz."),
    relatedIds: ["org_jandarma"],
    relatedEvents: ["hist_bitlis"],
    knownBy: ["askeri"],
    discoverability: "hidden",
    developerNotes: "Playable değil. Araştırma DB. Bağ kilitleme yok.",
    fiction: false,
  },
  {
    id: "per_koman",
    kind: "person",
    nodeKind: "kisi",
    displayName: "Teoman Koman",
    realPerson: true,
    factionId: "mit",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_pipo", "src_eymur"],
    sourceLocation: "Pipo; Eymür hattı",
    role: "MİT müsteşarlık hattı. Kamu görev.",
    summary: "Kurumsal üst. JİTEM sözcüsü değildir.",
    provenance: {
      historicalFact: "MİT’te üst düzey kamu görevi kaynaklarda geçer.",
      sourceClaim: "Abas dönemi kurum içi hatlarla birlikte anılır.",
      gameReconstruction: "MİT faction’ının kurumsal gölgesi. Haritada yok.",
      contradictions: ["JİTEM eşgüdümü varsayılmaz."],
    },
    motivation: unk("Kurumsal niyet kaynak dışı doldurulmaz."),
    relatedIds: ["org_mit", "per_abas"],
    knownBy: ["mit"],
    discoverability: "hidden",
    fiction: false,
  },
];

export const EXTRA_ORGS: ResearchRecord[] = [
  {
    id: "org_ozel_harekat",
    playId: "ozel_harekat",
    kind: "org",
    nodeKind: "kurum",
    displayName: "Özel Harekât",
    realPerson: false,
    factionId: "emniyet",
    evidence: "BELGELİ",
    sourceIds: ["src_tbmm_susurluk"],
    sourceLocation: "kamu kurum kaydı",
    role: "Emniyet özel tim. JİTEM değildir.",
    summary: "Ayrı kurumsal hat. Eşgüdüm varsayılmaz.",
    provenance: {
      historicalFact: "Emniyet bünyesinde resmi birim.",
      sourceClaim: "1990’lar kesişimi ve Susurluk bağlamı.",
      gameReconstruction: "Emniyet kapasitesi kümesi.",
      contradictions: ["JİTEM ile birleştirme TARTIŞMALI."],
    },
    motivation: assume("Oyun: ayrı çıkar. Tek el yok."),
    relatedIds: ["org_emniyet", "per_sahin"],
    discoverability: "late",
    gameUnlock: { appearTurn: 8, bilgi: 36 },
    appearTurn: 8,
    fiction: false,
  },
  {
    id: "org_jandarma",
    kind: "org",
    nodeKind: "kurum",
    displayName: "Jandarma Genel Komutanlığı",
    realPerson: false,
    factionId: "askeri",
    evidence: "BELGELİ",
    sourceIds: ["src_jandarma_kamu"],
    sourceLocation: "kamu kurum kaydı",
    role: "Kamu kurumu. JİTEM iddiasının resmi çatısı değil, resmi çatı.",
    summary: "Resmi jandarma. Fiilî JİTEM iddiası bu kayıttan ‘vardır’ diye kilitlenmez.",
    provenance: {
      historicalFact: "Kamu güvenlik kurumu.",
      sourceClaim: "JİTEM’in jandarma istihbarat içinde fiilî doğduğu anlatılır.",
      gameReconstruction: "Askerî bürokrasi faction’ı. Resmi dil ve mesafe.",
      contradictions: ["Resmi varlık ile fiilî tim aynı şey değildir."],
    },
    motivation: sourced("Kamu görev — kurumsal mesafe."),
    relatedIds: ["org_jitem", "per_bitlis"],
    knownBy: ["askeri", "jitem"],
    discoverability: "early",
    fiction: false,
  },
  {
    id: "org_ozel_harp",
    kind: "org",
    nodeKind: "kurum",
    displayName: "Özel Harp Dairesi",
    realPerson: false,
    factionId: "askeri",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_turhan"],
    sourceLocation: "Turhan / özel harp eleştirisi",
    role: "Özel harp / stay-behind eleştirisinin kurumsal ucu.",
    summary: "JİTEM ile tek el birleştirilmez. Ayrı eleştiri hattı.",
    provenance: {
      historicalFact: "Askerî özel harp yapılanması kamu tartışmasındadır.",
      sourceClaim: "Stay-behind / kontrgerilla tek merkez anlatıları.",
      gameReconstruction: "Tek el komplo kilidi yok. Parçalı çıkar.",
      contradictions: ["JİTEM = Özel Harp denklemı TARTIŞMALI / bu dosyada kilitlenmez."],
    },
    motivation: unk("Kurumsal irade yazılmaz."),
    relatedIds: ["org_jitem"],
    knownBy: ["askeri"],
    discoverability: "hidden",
    fiction: false,
  },
  {
    id: "place_susurluk",
    kind: "place",
    nodeKind: "koridor",
    displayName: "Susurluk",
    realPerson: false,
    factionId: "emniyet",
    evidence: "BELGELİ",
    sourceIds: ["src_susurluk_kaza"],
    sourceLocation: "kaza kamu kaydı",
    date: "1996-11-03",
    role: "Görünürlük mekânı. Operatif komuta değil.",
    summary: "3 Kasım kazasının yeri. Çıpa mekân.",
    provenance: {
      historicalFact: "Balıkesir–Susurluk yolunda kaza. Kamu kaydı.",
      sourceClaim: "Kesişim ağının görünür hale geldiği nokta.",
      gameReconstruction: "Final mekânı. Yeni bağ üretmez; kilitler.",
      contradictions: [],
    },
    motivation: unk("Coğrafya niyet taşımaz."),
    relatedIds: ["per_catli", "per_kocadag"],
    relatedEvents: ["hist_susurluk"],
    knownBy: ["emniyet", "media", "hukuk"],
    discoverability: "late",
    fiction: false,
  },
];

export const EXTRA_CLAIMS: ClaimRecord[] = [
  {
    id: "clm_official_denial",
    title: "Resmi inkâr: yapı yoktur",
    evidence: "BELGELİ",
    sourceIds: ["src_dogan", "src_tbmm_susurluk"],
    sourceLocation: "kamu dili / resmi açıklamalar",
    aboutIds: ["org_jitem"],
    layer: "historicalFact",
    statement: "Uzun yıllar resmi dil JİTEM’in olmadığını söyler.",
    contradiction: "Fiilî varlık GÜÇLÜ tanıklık ve sonraki süreçle çelişir.",
    knownBy: ["jitem", "askeri", "siyaset"],
    worldStatus: "TRUE",
    fiction: false,
  },
  {
    id: "clm_agar_catli",
    title: "Ağar–Çatlı kesişimi",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk", "src_yalcin_reis"],
    sourceLocation: "komisyon + Reis",
    aboutIds: ["per_agar", "per_catli"],
    layer: "sourceClaim",
    statement: "Siyaset–emniyet–Çatlı kesişimi kaynaklarda geçer.",
    contradiction: "Emir-komuta ve bilgi derecesi TARTIŞMALI.",
    knownBy: ["emniyet", "siyaset"],
    discoverability: "late",
    worldStatus: "PARTIAL",
    fiction: false,
  },
  {
    id: "clm_staybehind",
    title: "Kontrgerilla / stay-behind tek el",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_turhan"],
    sourceLocation: "Turhan / özel harp eleştirisi",
    aboutIds: ["org_jitem"],
    layer: "sourceClaim",
    statement: "Özel harp ve gizli yapılanma eleştirisi tek merkez varsayar.",
    contradiction: "Bu oyun tek el komplo kilitlemez. Parçalı çıkar ağları.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_carkin_teams",
    title: "Özel tim tanıklığı JİTEM’e bağ",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_carkin"],
    sourceLocation: "Çarkın tanıklığı",
    aboutIds: ["per_carkin", "org_jitem"],
    layer: "sourceClaim",
    statement: "Özel tim anlatısı bazen jandarma hattına yedirilir.",
    contradiction: "Kurumlar ayrı. Zorla birleştirme TARTIŞMALI.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_bitlis_sabotaj",
    title: "Bitlis uçak kazası sabotajdır",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_bitlis_kaza"],
    sourceLocation: "kamu kaydı sonrası iddia hattı",
    aboutIds: ["per_bitlis"],
    layer: "sourceClaim",
    statement: "Kazanın sabotaj olduğu iddiaları dolaşır.",
    contradiction: "Ölüm BELGELİ, neden TARTIŞMALI. Oyun neden kilitlemez.",
    worldStatus: "UNKNOWN",
    discoverability: "mid",
    fiction: false,
  },
  {
    id: "clm_bitlis_jitem",
    title: "Bitlis ölümü JİTEM hattına bağlıdır",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_bitlis_kaza", "src_yalcin_ersever"],
    sourceLocation: "kamu kaydı + saha anlatılarının yan yana okunması",
    aboutIds: ["per_bitlis", "org_jitem"],
    layer: "sourceClaim",
    statement: "Bazı anlatılar kazayı jandarma istihbarat gerilimine bağlar.",
    contradiction: "Bağ belgesizdir. Bu dosyada üretilmez.",
    worldStatus: "UNKNOWN",
    fiction: false,
  },
  {
    id: "clm_eymur_abas_split",
    title: "MİT içi Abas–Eymür hattı gerilimi",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_pipo", "src_eymur"],
    sourceLocation: "Pipo; Eymür yazıları",
    aboutIds: ["per_abas", "per_eymur", "org_mit"],
    layer: "sourceClaim",
    statement: "MİT tek yürek değildir; iç hat gerilimi kaynaklıdır.",
    contradiction: "Gerilim jandarma masasına otomatik bağlanmaz.",
    knownBy: ["mit"],
    worldStatus: "TRUE",
    fiction: false,
  },
  {
    id: "clm_informant_layer",
    title: "İtirafçı tim katmanı",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_aygan", "src_yalcin_ersever"],
    sourceLocation: "Aygan; Ersever kasetleri",
    aboutIds: ["per_aygan", "org_jitem"],
    layer: "sourceClaim",
    statement: "Saha resmi birliğin yanında itirafçı timleriyle genişler.",
    contradiction: "Her olayın yazılı emirle yapıldığı iddiası ZAYIF’tır.",
    knownBy: ["jitem"],
    worldStatus: "TRUE",
    discoverability: "early",
    fiction: false,
  },
  {
    id: "clm_dogan_founder",
    title: "Doğan kurucu rolü",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_dogan"],
    sourceLocation: "Doğan anlatımı",
    aboutIds: ["per_dogan", "org_jitem"],
    layer: "sourceClaim",
    statement: "Kendi anlatımında JİTEM’i kurduğunu söyler.",
    contradiction: "Kuruluş belgesi BOŞLUK. Saha hattı (Ersever) ayrı durur.",
    worldStatus: "PARTIAL",
    fiction: false,
  },
  {
    id: "clm_yesil_kayip",
    title: "Yeşil’in sonraki kaybı / kaçış iddiası",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_pekmezci"],
    sourceLocation: "Pekmezci hattı",
    aboutIds: ["per_yesil"],
    layer: "sourceClaim",
    statement: "Operatif profil sonraki yıllarda kayıp/kaçış anlatılarıyla geçer.",
    contradiction: "Bu kampanyanın 1986–96 omurgasını kilitlemez. Emir uydurulmaz.",
    worldStatus: "PARTIAL",
    discoverability: "late",
    fiction: false,
  },
  {
    id: "clm_ersever_tapes",
    title: "Ersever–Yalçın kaset hattı",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_ersever"],
    sourceLocation: "Binbaşı Ersever’in İtirafları / Haziran 1993 kaset hattı",
    aboutIds: ["per_ersever", "org_jitem"],
    layer: "historicalFact",
    statement: "Haziran 1993’te kaset/röportaj hattı döner. Konuşan içeridekidir.",
    contradiction: "Bastırma kaseti yok etmez; resmi inkâr hâlâ ‘yok’ der.",
    relatedEvents: ["hist_tapes"],
    relatedActors: ["per_ersever"],
    knownBy: ["jitem"],
    discoverability: "mid",
    worldStatus: "TRUE",
    developerNotes: "Event 6 + investigation documents + ending leakSuppressed.",
    fiction: false,
  },
  {
    id: "clm_abas_watch_withdrawn",
    title: "Abas suikastı öncesi takip ekibinin çekildiği iddiası",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_yalcin_pipo"],
    sourceLocation: "Pipo — tanıklık / anlatı hattı",
    aboutIds: ["per_abas", "org_mit"],
    layer: "sourceClaim",
    statement: "Bölgedeki takip ekibinin üç gün önce kaldırıldığı anlatılır.",
    contradiction: "Ölüm BELGELİ’dir; çekilme tanıklığı TARTIŞMALI durur. Fail/emir boşluğu kapanmaz.",
    relatedEvents: ["hist_abas"],
    relatedActors: ["per_abas", "per_eymur"],
    knownBy: ["mit"],
    discoverability: "mid",
    worldStatus: "UNKNOWN",
    developerNotes: "Event 5 + MIT faction knowledge. Researcher can verify to PARTIAL.",
    fiction: false,
  },
  {
    id: "clm_kocadag_catli_precrash",
    title: "Kocadağ–Çatlı kaza öncesi operasyonel ortaklık",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_yalcin_reis", "src_tbmm_susurluk"],
    sourceLocation: "Reis; TBMM Susurluk bağlamı",
    aboutIds: ["per_kocadag", "per_catli"],
    layer: "sourceClaim",
    statement: "Kazada kilitlenen bağ, kaza gecesinden önce de kaynaklarda operasyonel ortaklık olarak geçer.",
    contradiction: "Kaza BELGELİ kilitler; kaza öncesi emir-komuta TARTIŞMALI bırakılır.",
    relatedEvents: ["hist_susurluk"],
    relatedActors: ["per_kocadag", "per_catli"],
    knownBy: ["emniyet"],
    discoverability: "late",
    worldStatus: "PARTIAL",
    developerNotes: "Edge catli-kocadag + investigation + ending.",
    fiction: false,
  },
  {
    id: "clm_eymur_emniyet_warn",
    title: "Eymür’ün Emniyet–yeraltı uyarısı",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_eymur", "src_yalcin_reis"],
    sourceLocation: "Eymür yazıları; Reis hattı ile yan yana",
    aboutIds: ["per_eymur", "org_emniyet", "per_catli"],
    layer: "sourceClaim",
    statement: "Eymür, emniyet–yeraltı kesişimine dair uyarı yazar. Jandarma sözcüsü değildir.",
    contradiction: "Uyarı, jandarma ile emniyetin aynı masa olduğunu kanıtlamaz. Eşgüdüm uydurulmaz.",
    relatedEvents: ["hist_susurluk"],
    relatedActors: ["per_eymur", "per_catli"],
    knownBy: ["mit"],
    discoverability: "late",
    worldStatus: "TRUE",
    developerNotes: "Event 8 + faction media/emniyet + researcher compare.",
    fiction: false,
  },
  {
    id: "clm_tbmm_commission",
    title: "TBMM Susurluk komisyonu",
    evidence: "BELGELİ",
    sourceIds: ["src_tbmm_susurluk", "src_susurluk_kaza"],
    sourceLocation: "TBMM tutanakları / kamu kaydı",
    aboutIds: ["per_catli", "per_kocadag", "per_bucak"],
    layer: "historicalFact",
    statement: "Kaza sonrası meclis karesi açılır. Komisyon, inkâr ve parçalı kabul aynı anda yürür.",
    contradiction: "Komisyon adaleti tamamlamaz. Bazı bağlar kilitlenir, bazı emirler boşlukta kalır.",
    relatedEvents: ["hist_susurluk"],
    knownBy: ["hukuk", "media", "siyaset"],
    discoverability: "late",
    worldStatus: "TRUE",
    developerNotes: "Event 10 + hukuk hat + ending kismi_adalet.",
    fiction: false,
  },
  {
    id: "clm_aygan_dogan_split",
    title: "Aygan saha tanıklığı / Doğan idari anlatı ayrımı",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_aygan", "src_dogan"],
    sourceLocation: "Aygan tanıklığı; Doğan anlatımı",
    aboutIds: ["per_aygan", "per_dogan", "org_jitem"],
    layer: "sourceClaim",
    statement: "İki kaynak aynı yapıyı farklı uçtan anlatır: saha tim/itirafçı (Aygan) ve idari kurucu masa (Doğan).",
    contradiction: "İki anlatı birbirini otomatik doğrulamaz. Kuruluş belgesi BOŞLUK durur; emir uydurulmaz.",
    relatedActors: ["per_aygan", "per_dogan"],
    relatedEvents: ["hist_formation"],
    knownBy: ["jitem"],
    discoverability: "early",
    worldStatus: "PARTIAL",
    developerNotes: "Researcher compare loop. Faction media/hukuk notice. Does not mint a founder.",
    fiction: false,
  },
  {
    id: "clm_kutlu_vs_official",
    title: "Kutlu Savaş teftişi / resmi yok dili",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_kutlu_savas", "src_dogan"],
    sourceLocation: "Başbakanlık teftiş raporu hattı; resmi inkâr dili",
    aboutIds: ["org_jitem"],
    layer: "sourceClaim",
    statement: "Teftiş parçalı tespit üretir. Resmi dil uzun süre yok der.",
    contradiction: "Teftiş JİTEM adını kilitlemez. Parçalı kabul ile inkâr aynı anda yürür; adalet tamamlanmaz.",
    relatedEvents: ["hist_susurluk"],
    knownBy: ["hukuk", "siyaset"],
    discoverability: "mid",
    worldStatus: "PARTIAL",
    developerNotes: "Lawyer chain + fam_source_clash / fam_document_chain. Ending kismi_adalet.",
    fiction: false,
  },
  {
    id: "clm_hanefi_emniyet_split",
    title: "Emniyet içi anlatı JİTEM’e yedirilmez",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_hanefi", "src_tbmm_susurluk"],
    sourceLocation: "Hanefi Avcı anlatısı; TBMM Susurluk bağlamı",
    aboutIds: ["org_emniyet", "org_jitem"],
    layer: "sourceClaim",
    statement: "Emniyet içi anlatı 86–96 omurgasına geriye dönük kilitleme üretmez. Kurumlar ayrı durur.",
    contradiction: "Geç dönem anlatı, jandarma saha hattını emniyet özel timine eşitlemez. Eşgüdüm uydurulmaz.",
    relatedEvents: ["hist_susurluk"],
    knownBy: ["emniyet"],
    discoverability: "late",
    worldStatus: "UNKNOWN",
    developerNotes: "Researcher compare late. Stops folding Çarkın/Hanefi into JİTEM.",
    fiction: false,
  },
];

export const EXTRA_RELATIONS: RelationRecord[] = [
  {
    id: "rel_agar_emniyet",
    playId: "agar-emniyet",
    fromPlayId: "agar",
    toPlayId: "emniyet",
    label: "siyaset / emniyet",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk"],
    sourceLocation: "kamu görev",
    layer: "sourceClaim",
    appearTurn: 8,
  },
  {
    id: "rel_sahin_emniyet",
    playId: "sahin-emniyet",
    fromPlayId: "sahin",
    toPlayId: "emniyet",
    label: "özel harekât",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk"],
    sourceLocation: "kadrosal",
    layer: "historicalFact",
    appearTurn: 8,
  },
  {
    id: "rel_sahin_catli",
    playId: "sahin-catli",
    fromPlayId: "sahin",
    toPlayId: "catli",
    label: "kesişim",
    evidence: "GÜÇLÜ",
    sourceIds: ["src_tbmm_susurluk", "src_yalcin_reis"],
    sourceLocation: "Susurluk bağlamı",
    layer: "sourceClaim",
    appearTurn: 8,
  },
  {
    id: "rel_agar_catli",
    playId: "agar-catli",
    fromPlayId: "agar",
    toPlayId: "catli",
    label: "koruma iddiası",
    evidence: "TARTIŞMALI",
    sourceIds: ["src_tbmm_susurluk", "src_yalcin_reis"],
    sourceLocation: "komisyon iddiaları",
    layer: "sourceClaim",
    appearTurn: 8,
  },
];

export const HISTORY: HistoryRecord[] = [
  { id: "hist_formation", title: "Fiilî oluşum", date: "1986–88", evidence: "GÜÇLÜ", sourceIds: ["src_dogan", "src_yalcin_ersever"], sourceLocation: "Doğan + Ersever", layer: "sourceClaim", statement: "Jandarma istihbarat içinde fiilî tim/itirafçı yapı.", contradiction: "Kuruluş belgesi BOŞLUK.", relatedIds: ["org_jitem"], fiction: false },
  { id: "hist_command", title: "1990 komuta kayması", date: "1990", evidence: "TARTIŞMALI", sourceIds: ["src_dogan", "src_yalcin_ersever"], layer: "sourceClaim", statement: "Doğan ayrılışı / Küçük hattı iddiası.", contradiction: "Detay TARTIŞMALI.", relatedIds: ["per_dogan", "per_veli"], fiction: false },
  { id: "hist_abas", title: "Abas suikastı", date: "1990-09-26", evidence: "BELGELİ", sourceIds: ["src_yalcin_pipo"], sourceLocation: "Pipo", layer: "historicalFact", statement: "Hiram Abas İstanbul’da öldürüldü.", contradiction: "Fail/emir TARTIŞMALI.", relatedIds: ["per_abas"], fiction: false },
  { id: "hist_mumcu", title: "Mumcu suikastı", date: "1993-01-24", evidence: "BELGELİ", sourceIds: ["src_mumcu"], layer: "historicalFact", statement: "Uğur Mumcu bomba ile öldürüldü.", contradiction: "JİTEM bağ TARTIŞMALI.", relatedIds: ["per_mumcu"], fiction: false },
  { id: "hist_tapes", title: "Ersever kasetleri", date: "1993-06", evidence: "GÜÇLÜ", sourceIds: ["src_yalcin_ersever"], sourceLocation: "Binbaşı Ersever’in İtirafları", layer: "sourceClaim", statement: "Haziran 1993 konuşma/kaset.", contradiction: "Emir zinciri boşluğu durur.", relatedIds: ["per_ersever"], fiction: false },
  { id: "hist_ersever_death", title: "Ersever, Boz, itirafçı", date: "1993-11", evidence: "BELGELİ", sourceIds: ["src_yalcin_ersever", "src_pekmezci"], layer: "historicalFact", statement: "Cesetler bulundu.", contradiction: "Fail Yeşil GÜÇLÜ; emir TARTIŞMALI.", relatedIds: ["per_ersever", "per_nevval"], fiction: false },
  { id: "hist_susurluk", title: "Susurluk kazası", date: "1996-11-03", evidence: "BELGELİ", sourceIds: ["src_susurluk_kaza", "src_tbmm_susurluk"], layer: "historicalFact", statement: "Aynı araç: Kocadağ, Bucak, Çatlı, Gonca Us.", contradiction: null, relatedIds: ["per_catli", "per_kocadag", "per_bucak", "per_gonca"], fiction: false },
  { id: "hist_commission", title: "TBMM komisyonu", date: "1996–97", evidence: "BELGELİ", sourceIds: ["src_tbmm_susurluk"], sourceLocation: "TBMM tutanakları", layer: "historicalFact", statement: "Meclis soruşturması kuruldu.", contradiction: "Parçalı itiraf, tek çözüm yok.", relatedIds: ["org_tbmm"], fiction: false },
  { id: "hist_bitlis", title: "Eşref Bitlis uçak kazası", date: "1993-02-17", evidence: "BELGELİ", sourceIds: ["src_bitlis_kaza"], sourceLocation: "kamu kaydı / basın", layer: "historicalFact", statement: "Jandarma Genel Komutanı uçak kazasında öldü.", contradiction: "Sabotaj ve JİTEM bağ iddiaları TARTIŞMALI.", relatedIds: ["per_bitlis"], fiction: false },
  { id: "hist_pkk_1984", title: "PKK silahlı mücadelesinin yükseldiği zemin", date: "1984–", evidence: "BELGELİ", sourceIds: ["src_jandarma_kamu", "src_dogan"], sourceLocation: "kamu tarih / jandarma zemin", layer: "historicalFact", statement: "Güneydoğu’da silahlı çatışma ortamı kamu tarihidir.", contradiction: "Bu zemin JİTEM kuruluş belgesi değildir.", relatedIds: ["org_guneydogu"], fiction: false },
];
