import type { SourceRecord } from "./schema.ts";

export const SOURCES: SourceRecord[] = [
  {
    id: "src_yalcin_ersever",
    title: "Binbaşı Ersever’in İtirafları",
    author: "Soner Yalçın",
    year: "1994",
    kind: "book",
    note: "Haziran 1993 kaset/röportaj hattı. Saha anlatımı. Emir zinciri boşluğu durur.",
    location: "kitap / 1993 kaset hattı",
  },
  {
    id: "src_yalcin_pipo",
    title: "Pipo — Hiram Abas",
    author: "Soner Yalçın",
    year: "1990s",
    kind: "book",
    note: "Abas profili, MİT içi hatlar, 26 Eylül 1990 suikastı.",
    location: "kitap",
  },
  {
    id: "src_yalcin_reis",
    title: "Reis",
    author: "Soner Yalçın",
    kind: "book",
    note: "Çatlı hattı, sahte kimlik, Emniyet–yeraltı kesişimi.",
    location: "kitap",
  },
  {
    id: "src_dogan",
    title: "Arif Doğan anlatımı / JİTEM iddiası",
    author: "Arif Doğan",
    kind: "self",
    note: "İdari/kurucu rol iddiası. Kendi kitabı ve sonraki süreç tanıklıkları.",
    location: "anlatı / kitap / sonraki süreç",
  },
  {
    id: "src_eymur",
    title: "Eymür yazıları / atin.org hattı",
    author: "Mehmet Eymür",
    kind: "archive",
    note: "MİT kontrterör içi uyarılar. JİTEM sözcüsü değildir.",
    location: "yazı / arşiv hattı",
  },
  {
    id: "src_pekmezci",
    title: "Yeşil — Mahmut Yıldırım hattı",
    author: "Necdet Pekmezci",
    kind: "book",
    note: "Operatif profil, Ersever cinayeti fail iddiası.",
    location: "kitap",
  },
  {
    id: "src_aygan",
    title: "Abdülkadir Aygan tanıklığı",
    author: "Abdülkadir Aygan",
    kind: "testimony",
    note: "İtirafçı tim katmanı. Sonradan tanık.",
    location: "tanıklık",
  },
  {
    id: "src_mumcu",
    title: "Uğur Mumcu haber ve arşiv hattı",
    author: "Uğur Mumcu",
    kind: "press",
    note: "24 Ocak 1993 suikastı BELGELİ. Fail/emir TARTIŞMALI.",
    location: "haber arşivi / kamu kaydı",
  },
  {
    id: "src_turhan",
    title: "Talat Turhan / özel harp eleştirisi",
    author: "Talat Turhan",
    kind: "book",
    note: "Özel harp ve gayri resmi yapı eleştirisi. Komplo tek el üretmez.",
    location: "kitap / eleştiri hattı",
  },
  {
    id: "src_susurluk_kaza",
    title: "Susurluk kazası kamu kaydı",
    author: "kamu / basın",
    year: "1996-11-03",
    kind: "press",
    note: "3 Kasım 1996. Araç, kimlikler, silahlar. BELGELİ görünürlük.",
    location: "kaza tutanağı / basın",
  },
  {
    id: "src_tbmm_susurluk",
    title: "TBMM Susurluk komisyonu",
    author: "TBMM",
    year: "1997",
    kind: "commission",
    note: "Parçalı itiraf, inkâr, komisyon tutanakları. Tek doğru çözüm yok.",
    location: "TBMM tutanakları",
  },
  {
    id: "src_ergenekon",
    title: "Ergenekon süreci tanıklıkları",
    author: "yargı / tanık",
    kind: "testimony",
    note: "Geç dönem anlatılar. Geriye dönük iddia maliyeti yüksek; TARTIŞMALI işaretlenir.",
    location: "yargı / tanık dosyaları",
  },
  {
    id: "src_carkin",
    title: "Ayhan Çarkın tanıklığı",
    author: "Ayhan Çarkın",
    kind: "testimony",
    note: "Özel tim anlatısı. JİTEM’e zorla yedirilmez.",
    location: "basın röportaj / tanıklık hattı",
  },
  {
    id: "src_hanefi",
    title: "Hanefi Avcı anlatısı",
    author: "Hanefi Avcı",
    kind: "book",
    note: "Emniyet içi anlatı. 86–96 omurgasına geriye dönük kilitleme yok.",
    location: "kitap",
  },
  {
    id: "src_kutlu_savas",
    title: "Kutlu Savaş / Susurluk raporu hattı",
    author: "Kutlu Savaş",
    year: "1997",
    kind: "commission",
    note: "Resmi teftiş. Parçalı tespit.",
    location: "Başbakanlık teftiş raporu hattı",
  },
  {
    id: "src_bitlis_kaza",
    title: "Eşref Bitlis uçak kazası kamu kaydı",
    author: "kamu / basın",
    year: "1993-02-17",
    kind: "press",
    note: "Ölüm BELGELİ. Sabotaj ve JİTEM bağ iddiaları TARTIŞMALI bırakılır.",
    location: "kamu kaydı / basın",
  },
  {
    id: "src_jandarma_kamu",
    title: "Jandarma Genel Komutanlığı kamu kaydı",
    author: "kamu",
    kind: "archive",
    note: "Kamu kurumu. JİTEM fiilî iddiası bu kayıttan doğmaz.",
    location: "kamu kurum kaydı",
  },
];

export const SOURCE_BY_ID = Object.fromEntries(SOURCES.map((s) => [s.id, s]));
